#!/usr/bin/env python
"""The board — the DERIVED tracks × phases view (WF-1, dn-track-board-and-deskcheck-gate D2).

A DERIVED view, recomputed from the artifact tree on every run: NO persisted state, so it
cannot drift (the falsifier F-WF2) — the same stance as `scripts/docket.py:4-6`. It renders
BOTH board files from front matter + the `docs/tracks/<slug>.md` manifests + any deskcheck
records:

    docs/TRACKS.md          -- the board: swim lanes = tracks; per member its computed phase
    docs/DESKCHECK-QUEUE.md -- the owed-deskcheck inbox: deskcheck-pending tracks + standing backlog

Front-matter parsing is REUSED from `.claude/hooks/_lib.py` (DRY, plan §2 audit) — this script
never re-derives a YAML parser and never imports `core` (repo-workflow tooling, mirror docket).

    uv run scripts/board.py                # render both views to stdout (for inspection)
    uv run scripts/board.py --write        # write docs/TRACKS.md + docs/DESKCHECK-QUEUE.md
    uv run scripts/board.py --queue-count  # print ONE integer: # tracks owed a deskcheck
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Reuse the artifact front-matter machinery — never re-derive it (plan §2 DRY audit).
sys.path.insert(0, str(ROOT / ".claude" / "hooks"))
from _lib import (  # type: ignore[import-not-found]  # noqa: E402
    _normalize_status,
    parse_front_matter,
)

# The generated files never exceed this table-row width (owner rule 2026-07-21): terse cells,
# detail in the prose beneath. A row that would exceed it is truncated with an ellipsis.
MAX_ROW = 190

GENERATED_BANNER = "<!-- GENERATED by scripts/board.py — do not hand-edit -->"

# The phase's required model tier (dn-track-board-and-deskcheck-gate D2/D7 — rendered so a
# tier mismatch is visible at a glance; the tier is a *requirement*, not a derivation of who ran).
PHASE_MODEL: dict[str, str] = {
    "design-pass": "FABLE",
    "graduate": "Fable/Opus",
    "build": "opus",
    "deskcheck-pending": "opus",
    "dormant": "—",
    "CLOSED": "—",
}


def _is_absent(v: object) -> bool:
    """`_lib.parse_front_matter` yields the literal string ``"null"`` for a YAML ``null`` (it
    does not interpret scalars). Treat that, an empty string, ``none`` and ``~`` as absent."""
    if v is None:
        return True
    if isinstance(v, str):
        return v.strip().lower() in ("", "null", "none", "~")
    if isinstance(v, (list, tuple)):
        return len(v) == 0
    return False


def _text(v: object) -> str:
    return "" if _is_absent(v) else str(v).strip()


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


def _first_h1(text: str) -> str:
    for ln in text.splitlines():
        if ln.startswith("# "):
            return ln[2:].strip()
    return ""


def _status(fm: dict[str, object]) -> str | None:
    s = fm.get("status")
    if isinstance(s, str) and s:
        return _normalize_status(s)
    return None


def _cap(row: str, width: int = MAX_ROW) -> str:
    """Cap a rendered table row at ``width`` chars, truncating the content with an ellipsis
    while preserving the trailing ` |` cell border (owner ≤190 rule)."""
    if len(row) <= width:
        return row
    tail = " |"
    keep = width - len(tail) - 1  # room for the ellipsis
    return row[:keep].rstrip() + "…" + tail


# ── data model ──────────────────────────────────────────────────
@dataclass(frozen=True)
class Plan:
    id: str
    title: str  # H1 with the "Build Plan — " prefix already stripped
    status: str


@dataclass(frozen=True)
class DeskCheck:
    id: str
    track: str
    verdict: str


@dataclass
class Track:
    slug: str
    title: str
    status: str  # manifest status: active | dormant-by-design
    warrant: str
    dod: list[str]
    backlog: str  # the standing owed-deskcheck statement ("" if absent)
    audit_refs: list[str]
    note_statuses: list[str] = field(default_factory=list)
    plans: list[Plan] = field(default_factory=list)

    @property
    def lane(self) -> str:
        """The short swim-lane label — the manifest title before its ' — ' dash."""
        return self.title.split(" — ", 1)[0].strip() or self.slug


# ── scanning ────────────────────────────────────────────────────
def _scan_manifests(root: Path) -> dict[str, Track]:
    tracks: dict[str, Track] = {}
    for mf in sorted(root.glob("docs/tracks/*.md")):
        fm = parse_front_matter(_read(mf))
        if fm.get("type") != "track":
            continue
        slug = _text(fm.get("slug")) or mf.stem
        dod = [str(x) for x in (fm.get("dod") or []) if not _is_absent(x)]
        audit = [str(x) for x in (fm.get("audit_refs") or []) if not _is_absent(x)]
        tracks[slug] = Track(
            slug=slug,
            title=_text(fm.get("title")) or slug,
            status=_text(fm.get("status")) or "active",
            warrant=_text(fm.get("warrant")),
            dod=dod,
            backlog=_text(fm.get("backlog_deskcheck")),
            audit_refs=audit,
        )
    return tracks


_PLAN_PREFIX = "Build Plan — "


def _attach_plans(root: Path, tracks: dict[str, Track]) -> list[str]:
    """Attach each plan to its track; return the list of orphan slugs (a `track:` value with
    no manifest — the F-WF1 coordinate-split signal)."""
    orphans: list[str] = []
    for plan in sorted(root.glob("docs/build-plans/*/plan.md")):
        text = _read(plan)
        fm = parse_front_matter(text)
        slug = _text(fm.get("track"))
        if not slug:
            continue
        title = _first_h1(text)
        if title.startswith(_PLAN_PREFIX):
            title = title[len(_PLAN_PREFIX):]
        p = Plan(
            id=str(fm.get("id") or plan.parent.name),
            title=title,
            status=_status(fm) or "?",
        )
        if slug in tracks:
            tracks[slug].plans.append(p)
        else:
            orphans.append(f"{p.id} → track: {slug} (no docs/tracks/{slug}.md manifest)")
    for t in tracks.values():
        t.plans.sort(key=lambda p: p.id)
    return orphans


def _attach_notes(root: Path, tracks: dict[str, Track]) -> list[str]:
    """Attach design-note statuses to their track; return orphan-note messages."""
    orphans: list[str] = []
    for note in sorted(root.glob("docs/design-notes/*.md")):
        fm = parse_front_matter(_read(note))
        slug = _text(fm.get("track"))
        if not slug:
            continue
        st = _status(fm) or "?"
        if slug in tracks:
            tracks[slug].note_statuses.append(st)
        else:
            orphans.append(f"{note.stem} → track: {slug} (no docs/tracks/{slug}.md manifest)")
    return orphans


def _scan_deskchecks(root: Path) -> list[DeskCheck]:
    out: list[DeskCheck] = []
    for dc in sorted(root.glob("docs/deskchecks/*.md")):
        fm = parse_front_matter(_read(dc))
        if fm.get("type") != "deskcheck":
            continue
        out.append(DeskCheck(
            id=str(fm.get("id") or dc.stem),
            track=_text(fm.get("track")),
            verdict=(_text(fm.get("verdict")) or "pending").lower(),
        ))
    return out


# ── the phase function (dn-track-board-and-deskcheck-gate D2) ─────
def plan_phase(status: str) -> str:
    """A single plan's phase from its status (the per-item board cell)."""
    if status == "complete":
        return "deskcheck-pending"  # sealed ⇒ owes a deskcheck (no approved dc yet)
    if status in ("ready", "in-progress"):
        return "build"
    if status == "proposed":
        return "graduate"
    return status


def track_phase(t: Track, dcs: list[DeskCheck]) -> str:
    """The track-level phase (the D2 table). Drives the queue and the no-plan lane cell."""
    if t.status == "dormant-by-design":
        return "dormant"
    approved = any(d.verdict == "approved" and d.track == t.slug for d in dcs)
    if approved:  # closure is COMPUTED: an approved dc names the track (DoD = owner's call)
        return "CLOSED"
    if any(s == "draft" for s in t.note_statuses):
        return "design-pass"
    plan_st = [p.status for p in t.plans]
    if plan_st and any(s in ("ready", "in-progress") for s in plan_st):
        return "build"
    if plan_st and all(s == "complete" for s in plan_st):
        return "deskcheck-pending"
    if any(s == "ratified" for s in t.note_statuses) and (
        not plan_st or any(s == "proposed" for s in plan_st)
    ):
        return "graduate"
    return "design-pass"  # no plans, no draft note ⇒ design work is owed


def is_owed(t: Track, dcs: list[DeskCheck]) -> bool:
    """A track owes a deskcheck iff its computed phase is deskcheck-pending OR it carries a
    standing backlog statement (an earlier sealed wave whose deskcheck is still owed) — the
    §6 queue definition ("deskcheck-pending + backlog"). Dormant tracks with a confirm-only
    backlog are owed too (confirm dormancy)."""
    return track_phase(t, dcs) == "deskcheck-pending" or bool(t.backlog)


# ── rendering ───────────────────────────────────────────────────
def _sorted_tracks(tracks: dict[str, Track]) -> list[Track]:
    # active/building lanes first, dormant last, alphabetical within — deterministic (idempotent).
    return sorted(tracks.values(), key=lambda t: (t.status == "dormant-by-design", t.slug))


_PHASE_PIPELINE = """\
## The phase pipeline (owner spec 2026-07-21) — and the model each phase requires

| # | phase | model | what happens | artifact |
|---|---|---|---|---|
| 1 | **brainstorm** | any | capture an idea | `docs/brainstorms/` |
| 2 | **design-pass** | **FABLE** | discuss → design note; owner ratifies | notes (draft→ratified) |
| 3 | **graduate** | Fable/Opus | decompose a ratified note → plans | plans (proposed→ready) |
| 4 | **build** | right model | execute a build plan | journal + seal |
| 5 | **audit** | Opus/Fable | check it was built to spec | finding / audit note |
| 6 | **deskcheck** | **Opus** | demo to the owner; approve or send back | owner verdict |
| → | **CLOSED** | — | owner-approved; the track is complete | — |

**Cross-cutting item types (routed as before, not linear phases):** OQ
(`docs/inbox/owner-questions.md`, surfaced by `scripts/docket.py`) · findings
(`docs/findings/`; codebase/spec-fidelity → builder, design/math/direction → orchestrator)."""


def render_board(tracks: dict[str, Track], dcs: list[DeskCheck], orphans: list[str]) -> str:
    out = [GENERATED_BANNER, ""]
    out.append("# The board — tracks × phases (the JIRA-like swim-lane board)")
    out.append("")
    out.append(
        "> A **derived view** — recomputed from the artifact tree by `scripts/board.py`, never "
        "hand-maintained. To move a card: edit the artifact's `track:` / `status:` front matter "
        "or its `docs/tracks/<slug>.md` manifest, then regenerate (`uv run scripts/board.py "
        "--write`). Swim lanes = tracks; the phase is computed per member. A **track is CLOSED "
        "only when an owner-approved deskcheck names it** — never self-closed."
    )
    out.append("")
    out.append(_PHASE_PIPELINE)
    out.append("")
    out.append("## Active board (swim lanes = tracks)")
    out.append("")
    out.append("| track | item | phase | model |")
    out.append("|---|---|---|---|")
    for t in _sorted_tracks(tracks):
        if t.plans:
            for p in t.plans:
                ph = plan_phase(p.status)
                model = PHASE_MODEL.get(ph, "—")
                item = f"{p.id} — {p.title}" if p.title else p.id
                out.append(_cap(f"| {t.lane} | {item} | {ph} · {p.status} | {model} |"))
        else:
            ph = track_phase(t, dcs)
            model = PHASE_MODEL.get(ph, "—")
            detail = t.title.split(" — ", 1)[1].strip() if " — " in t.title else t.slug
            note = " (dormant-by-design)" if t.status == "dormant-by-design" else ""
            out.append(_cap(f"| {t.lane} | {detail}{note} | {ph} | {model} |"))
    out.append("")

    # The definition-of-done per track — preserves every DoD fact (e.g. code-ingest's
    # "integrator densification (finding-0151)") that is not itself a plan row.
    out.append("## Definition of done (per track — the deskcheck evaluates against this)")
    out.append("")
    for t in _sorted_tracks(tracks):
        if not t.dod:
            continue
        warrant = f" · warrant {t.warrant}" if t.warrant else ""
        out.append(f"- **{t.lane}** ({t.status}{warrant}):")
        for d in t.dod:
            out.append(f"    - {d}")
    out.append("")

    # Closed — computed: an approved dc names the track. None yet ⇒ the discipline starts here.
    closed = [t for t in _sorted_tracks(tracks) if track_phase(t, dcs) == "CLOSED"]
    out.append("## Closed (owner-approved deskchecks)")
    out.append("")
    if closed:
        out.append("| track | closed by |")
        out.append("|---|---|")
        for t in closed:
            names = ", ".join(d.id for d in dcs if d.track == t.slug and d.verdict == "approved")
            out.append(_cap(f"| {t.lane} | {names} |"))
    else:
        out.append("_(none yet — a track closes only on an owner-approved deskcheck.)_")
    out.append("")

    # Coordinate check (F-WF1): any `track:` slug with no manifest, or a manifest with no members.
    out.append("## Coordinate check (orphans)")
    out.append("")
    no_member = [
        t.slug for t in _sorted_tracks(tracks)
        if not t.plans and not t.note_statuses and t.status != "dormant-by-design"
    ]
    if orphans or no_member:
        for o in orphans:
            out.append(f"- ⚠ artifact with no manifest: {o}")
        for slug in no_member:
            out.append(
                f"- (info) manifest `{slug}` has no plan/note members yet — carried by manifest "
                f"(design-pass queued); not an error while its work is pre-plan."
            )
    else:
        out.append("_No orphans: every `track:` slug has a manifest, every manifest has members._")
    out.append("")
    out.append("_Derived by `scripts/board.py` from front matter + `docs/tracks/` manifests + "
               "`docs/deskchecks/`. Never hand-edit; edit the sources and regenerate._")
    return "\n".join(out) + "\n"


def render_queue(tracks: dict[str, Track], dcs: list[DeskCheck]) -> str:
    owed = [t for t in _sorted_tracks(tracks) if is_owed(t, dcs)]
    out = [GENERATED_BANNER, ""]
    out.append("# Deskchecks owed — the persistent inbox")
    out.append("")
    out.append(
        "> A **derived view** (`scripts/board.py`) — the deskcheck analog of "
        "`docs/inbox/owner-questions.md`. These are demonstrations owed to the owner to *close* a "
        "track. Surfaced **every session** (the resume brief / session-brief owed-count) and at "
        "every `/triage`, and kept raised until the owner acts — a track is not closed until its "
        "deskcheck is approved. The full track picture is the board (`docs/TRACKS.md`)."
    )
    out.append(">")
    out.append(
        "> Verdict: `PENDING` (owed) · an owner-approved `dc-NNN` moves the track to the board's "
        "Closed section · `NEEDS-WORK` sends it back to an earlier phase."
    )
    out.append("")
    out.append(f"## Owed now — {len(owed)} track(s)")
    out.append("")
    if owed:
        out.append("| # | track | what to demo (working / true state) + surprise | verdict |")
        out.append("|---|---|---|---|")
        for i, t in enumerate(owed, 1):
            demo = t.backlog or f"sealed work ({track_phase(t, dcs)}); confirm delivered"
            out.append(_cap(f"| {i} | {t.lane} | {demo} | PENDING |"))
    else:
        out.append("_(none owed — inbox zero.)_")
    out.append("")

    # Tracks in build whose plans enter the queue at seal.
    building = [
        t for t in _sorted_tracks(tracks)
        if track_phase(t, dcs) == "build" and not is_owed(t, dcs)
    ]
    out.append("## Owed on completion — the current build tracks")
    out.append("")
    if building:
        names = ", ".join(t.lane for t in building)
        out.append(
            f"Every plan in the board's `build` phase enters this inbox at seal "
            f"(`build → audit → deskcheck`): {names}. The orchestrator adds the row and says "
            f'"ready to deskcheck" when a track reaches phase 6. None is closed by sealing.'
        )
    else:
        out.append("_(no build-phase tracks pending completion.)_")
    out.append("")
    out.append("_Derived by `scripts/board.py`; never hand-edit. This is the "
               "deskcheck-pending-or-backlog filter over the board._")
    return "\n".join(out) + "\n"


# ── driver ──────────────────────────────────────────────────────
def _build(root: Path) -> tuple[dict[str, Track], list[DeskCheck], list[str]]:
    tracks = _scan_manifests(root)
    orphans = _attach_plans(root, tracks) + _attach_notes(root, tracks)
    dcs = _scan_deskchecks(root)
    return tracks, dcs, orphans


def board_text(root: Path) -> str:
    tracks, dcs, orphans = _build(root)
    return render_board(tracks, dcs, orphans)


def queue_text(root: Path) -> str:
    tracks, dcs, _ = _build(root)
    return render_queue(tracks, dcs)


def queue_count(root: Path) -> int:
    tracks, dcs, _ = _build(root)
    return sum(1 for t in tracks.values() if is_owed(t, dcs))


def main(argv: list[str]) -> int:
    if "--queue-count" in argv:
        print(queue_count(ROOT))
        return 0
    if "--write" in argv:
        (ROOT / "docs" / "TRACKS.md").write_text(board_text(ROOT), encoding="utf-8")
        (ROOT / "docs" / "DESKCHECK-QUEUE.md").write_text(queue_text(ROOT), encoding="utf-8")
        print(f"wrote docs/TRACKS.md + docs/DESKCHECK-QUEUE.md (queue: {queue_count(ROOT)})")
        return 0
    sys.stdout.write(board_text(ROOT))
    sys.stdout.write("\n")
    sys.stdout.write(queue_text(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
