#!/usr/bin/env python
"""The handoff — the DERIVED per-scope rendering (dn-role-state-and-scoped-handoff §2.9, bp-124).

The seat outlives the occupant. This is the half of a seat's state that no one should ever
*remember*: a deterministic rendering of what the artifact tree already says, regenerated instead
of hand-carried. Its siblings are `docs/roles/<role>/journal.md` (NARRATIVE — judgement no
generator can write) and `readings.md` (MEASURED — the result of running something, with its age
attached). This file is the third: DERIVED.

    uv run scripts/handoff.py --role orchestrator            # the LIVE pane, to stdout
    uv run scripts/handoff.py --role orchestrator --write    # docs/roles/orchestrator/handoff.md
    uv run scripts/handoff.py --role orchestrator --check    # byte-compare; exit 0 == identical
    uv run scripts/handoff.py --role orchestrator --json     # the structured answer, to stdout
    uv run scripts/handoff.py --track <slug>                 # stdout only — no standing file
    uv run scripts/handoff.py --plan <id>                    # stdout only — no standing file

⚑ THE IDEMPOTENCE PIN (§2.9, load-bearing for the whole family). The *committed* rendering is a
pure function of the artifact tree EXCLUDING ITSELF, and embeds **no HEAD sha and no generation
timestamp**. So regenerate-then-commit converges in one step, and a freshness gate that compares
the regeneration against the committed file can be discharged by one mechanical command instead of
re-arming forever. A rendering that embedded HEAD or `now()` would have no fixed point — the
defect this design exists to remove, mechanized.

Two consequences follow, and they are why `--write` / `--check` / `--json` render in TREE-PURE mode
while a bare `--role` renders LIVE (`_View.live`):

  * **The queue is an input, not the tree.** `data/queue.sqlite` is gitignored runtime state that a
    live supervisor mutates continuously, and it is absent from every worktree. Its depth in the
    committed file would go stale between two regenerations of an unchanged tree — the pin broken,
    and the gate re-armed by the daemon rather than by the work. So the live queue pane is stdout
    only; the committed rendering carries a pointer to it. Availability degrades gracefully either
    way: no queue file is a VALUE (`queue: unavailable in this checkout`), never an exception.
  * **An age is a clock read.** The live pane shows "(18h ago)" beside a reading; the committed
    rendering shows the reading's own timestamp, which is data carried by `readings.md` (§2.9:
    "readings carry their own timestamps as data").

Front-matter parsing is REUSED from `.claude/hooks/_lib.py` and the artifact scanners from
`scripts/board.py` — this script re-derives neither, and never imports `core` (repo-workflow
tooling, the docket/board stance).
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Reuse the artifact front-matter machinery — never re-derive it (plan §2 DRY audit).
sys.path.insert(0, str(ROOT / ".claude" / "hooks"))
sys.path.insert(0, str(ROOT / "scripts"))
import board  # type: ignore[import-not-found]  # noqa: E402
from _lib import _normalize_status  # type: ignore[import-not-found]  # noqa: E402

GENERATED_BANNER = "<!-- GENERATED by scripts/handoff.py — do not hand-edit -->"

# The closed role registry (note §2.4). `scheduler` is a seat whose state is ALREADY typed and
# durable in `data/queue.sqlite`; it gets no narrative artifact, and no directory is minted for it
# here — `--write` refuses a role whose seat directory does not already exist.
ROLE_REGISTRY: tuple[str, ...] = ("orchestrator", "scheduler")

QUEUE_UNAVAILABLE = "queue: unavailable in this checkout"
QUEUE_POINTER = (
    "queue: a live probe (MEASURED), deliberately not carried in the committed rendering — "
    "run `uv run scripts/handoff.py --role <role>` for the pane"
)
_Q_DEPTH = "SELECT count(*) FROM jobs WHERE state = 'queued'"
_Q_RUNNING = "SELECT id, kind, lease_expires_at FROM jobs WHERE state = 'running' ORDER BY id"

# Plan statuses that make a plan a *unit of work* rather than history, most urgent first. The
# ladder is the whole of `next_action`: one in-flight unit beats an available one, and an empty
# board means the sweep is owed. Deliberately three rungs — the owner-only gates (a blessing, a
# ratification) are NOT agent next-actions, so they surface in the owner-awaiting pane instead.
_LADDER: tuple[tuple[str, str], ...] = (("in-progress", "/resume"), ("ready", "/build"))

_NONE = "none"


class ScopeError(ValueError):
    """An unresolvable scope. A scope is `(kind, id)` where the id names an artifact ON DISK
    (note §2.3) — never a free string, so a typo fails loudly instead of rendering an empty view."""


@dataclass(frozen=True)
class Scope:
    kind: str  # role | plan | track
    id: str

    @property
    def label(self) -> str:
        return f"{self.kind}:{self.id}"


@dataclass(frozen=True)
class Answer:
    """The generator's own answer to the fresh-agent drill's probe (note §2.11 F2). Emitted as
    JSON so the drill has a mechanical ground truth to compare an agent's answer against, and
    rendered into the document from the SAME computation so the two can never disagree."""

    scope: str
    unit_in_flight: str  # a bare artifact id, or "none" — the compare-friendly form
    unit_title: str
    next_action: str  # a bare command, e.g. "/resume bp-123"
    blocking_unknowns: tuple[str, ...]

    def as_dict(self) -> dict[str, object]:
        return {
            "scope": self.scope,
            "unit_in_flight": self.unit_in_flight,
            "unit_title": self.unit_title,
            "next_action": self.next_action,
            "blocking_unknowns": list(self.blocking_unknowns),
        }


@dataclass(frozen=True)
class _View:
    """One rendering's mode. `live=False` is the committed, tree-pure artifact (the pin)."""

    live: bool


# ── scope resolution ────────────────────────────────────────────
def resolve(root: Path, kind: str, ident: str) -> Scope:
    if kind == "role":
        if ident not in ROLE_REGISTRY:
            raise ScopeError(f"unknown role '{ident}' — the registry is closed: "
                             f"{', '.join(ROLE_REGISTRY)} (note §2.4)")
    elif kind == "plan":
        if not (root / "docs" / "build-plans" / ident / "plan.md").exists():
            raise ScopeError(f"no such plan '{ident}' (docs/build-plans/{ident}/plan.md)")
    elif kind == "track":
        if not (root / "docs" / "tracks" / f"{ident}.md").exists():
            raise ScopeError(f"no such track '{ident}' (docs/tracks/{ident}.md)")
    else:  # pragma: no cover — argparse constrains the kind
        raise ScopeError(f"unknown scope kind '{kind}'")
    return Scope(kind, ident)


def seat_dir(root: Path, role: str) -> Path:
    return root / "docs" / "roles" / role


# ── the inputs ──────────────────────────────────────────────────
def _members(root: Path, scope: Scope) -> tuple[
    list[board.Plan], list[tuple[str, str]], list[str], list[tuple[str, str, dict[str, str]]]
]:
    """The scope's member artifacts: (plans, [(note-stem, status)], finding-stems, oq-entries).

    A `role` scope sees the whole tree (the orchestrator's remit is everything); a `track` scope
    sees exactly the artifacts declaring that slug — the derived join note §2.3 calls for, which
    is why findings and owner questions are read here and not only by the board's orphan check.
    """
    plans = [p for p, slug in board.scan_plans(root)
             if scope.kind != "track" or slug == scope.id]
    if scope.kind == "plan":
        plans = [p for p in plans if p.id == scope.id]
    notes = [(stem, st) for stem, st, slug in board.scan_notes(root)
             if scope.kind == "role" or (scope.kind == "track" and slug == scope.id)]
    findings = [stem for stem, st, slug in board.scan_findings(root)
                if _normalize_status(st) == "open"
                and (scope.kind == "role" or (scope.kind == "track" and slug == scope.id))]
    oqs = [e for e in board.scan_oqs(root)
           if _normalize_status(e[2].get("status", "")) == "open"
           and (scope.kind == "role" or (scope.kind == "track" and e[2].get("track") == scope.id))]
    return plans, notes, findings, oqs


def read_readings(path: Path) -> list[tuple[str, str, str]]:
    """The MEASURED log as `(timestamp, command, result)` rows, in file order (append-only)."""
    rows: list[tuple[str, str, str]] = []
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return rows
    for ln in text.splitlines():
        s = ln.strip()
        if not s.startswith("|"):
            continue
        cells = [c.strip() for c in s.strip("|").split("|")]
        if len(cells) != 3 or cells[0].lower() == "timestamp" or not set(cells[0]) - set("-: "):
            continue  # the table header and its separator row are not readings
        rows.append((cells[0], cells[1], cells[2]))
    return rows


def latest_per_command(rows: list[tuple[str, str, str]]) -> list[tuple[str, str, str]]:
    """The newest reading per command, command-ascending. "Newest" is LAST-IN-FILE, not the
    largest timestamp: the log is append-only, so file order already is chronological order —
    and taking it that way keeps the rendering independent of parsing a clock format."""
    latest: dict[str, tuple[str, str, str]] = {}
    for ts, cmd, result in rows:
        latest[cmd] = (ts, cmd, result)
    return [latest[c] for c in sorted(latest)]


def read_queue(path: Path) -> list[str]:
    """The live queue pane — READ-ONLY, and a missing file is a VALUE, never an exception.

    `mode=ro` is load-bearing twice over: the supervisor is the queue's single writer
    (`scheduler/queue.py:17-18`), and a plain `sqlite3.connect` would CREATE an empty
    `queue.sqlite` in any checkout that lacks one — the exact regression `read_queue_stats` was
    written to fix (`ops/lifecycle/snapshot.py:324-327`). This generator must be safe to run in a
    fresh worktree with nothing running, which is the availability constraint that decided the
    substrate (note §2.6).
    """
    if not path.exists():
        return [QUEUE_UNAVAILABLE]
    conn = None
    try:
        conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
        depth = conn.execute(_Q_DEPTH).fetchone()[0]
        running = conn.execute(_Q_RUNNING).fetchall()
    except sqlite3.Error as exc:
        return [f"queue: present but unreadable — {exc}"]
    finally:
        if conn is not None:
            conn.close()
    return [f"queue: depth {depth} · running {len(running)}"] + [
        f"queue: RUNNING {r[0]} · {r[1]} · lease {r[2] or _NONE}" for r in running]


def _age(stamp: str, now: datetime) -> str:
    """A human age for a reading's timestamp. LIVE VIEW ONLY — it reads the clock, which the
    idempotence pin forbids in the committed artifact."""
    for fmt in ("%Y-%m-%dT%H:%MZ", "%Y-%m-%dT%H:%M:%SZ", "%Y-%m-%d"):
        try:
            when = datetime.strptime(stamp, fmt).replace(tzinfo=UTC)
        except ValueError:
            continue
        hours = (now - when).total_seconds() / 3600.0
        if hours < 1:
            return f"{int(hours * 60)}m ago"
        return f"{int(hours)}h ago" if hours < 48 else f"{int(hours / 24)}d ago"
    return "age unknown"


# ── the derivation ──────────────────────────────────────────────
def derive(root: Path, scope: Scope) -> Answer:
    """The scope's answer to the drill's probe — a pure function of the artifact tree."""
    plans, notes, _findings, oqs = _members(root, scope)
    unit, title, action = _NONE, "", ""
    for status, cmd in _LADDER:
        hits = sorted((p for p in plans if p.status == status), key=lambda p: p.id)
        if hits:
            unit, title, action = hits[0].id, hits[0].title, f"{cmd} {hits[0].id}"
            break
    if not action:
        action = _fallback_action(scope, plans, notes)
    blocking = tuple(
        f"BLOCKED: {oid} — {title_}" for oid, title_, fields in oqs
        if fields.get("blocking", "").strip().lower() == "true"
    )
    return Answer(scope.label, unit, title, action, blocking)


def _fallback_action(scope: Scope, plans: list[board.Plan],
                     notes: list[tuple[str, str]]) -> str:
    """What is owed when no plan in this scope is in-progress or ready. For a `plan` scope the
    plan's own status decides; otherwise the sweep is owed (it is the act that batches the
    owner-only gates, which are never an agent's next action)."""
    if scope.kind == "plan":
        st = plans[0].status if plans else "?"
        return {
            "complete": f"deskcheck owed on {scope.id} — sealed, not closed",
            "proposed": f"owner blessing owed on {scope.id} (proposed→ready) — by hand, never in "
                        f"session",
            "superseded": f"nothing — {scope.id} is superseded",
        }.get(st, f"inspect {scope.id} (status: {st})")
    if scope.kind == "track" and any(st == "draft" for _stem, st in notes):
        return "/graduate is blocked — a draft note on this track is owed a ratification"
    return "/triage"


# ── rendering ───────────────────────────────────────────────────
def _table(out: list[str], header: str, sep: str, rows: list[str]) -> None:
    if not rows:
        out.append("_(none)_")
        return
    out.append(board._cap(header))
    out.append(sep)
    out.extend(board._cap(r) for r in rows)


def render(root: Path, scope: Scope, view: _View) -> str:
    plans, notes, findings, oqs = _members(root, scope)
    ans = derive(root, scope)
    tracks, dcs, _orphans = board._build(root)
    out: list[str] = [GENERATED_BANNER, "", f"# Handoff — {scope.label}", ""]
    out.append(
        "> A **DERIVED** view of the artifact tree, regenerated by `scripts/handoff.py` and never "
        "hand-edited. It carries **no commit sha and no generation timestamp** by design (the "
        "§2.9 idempotence pin): two renders of an unchanged tree are byte-identical, so "
        "regenerating is a no-op and `git log` stays the one derived view of commits. Judgement "
        "lives in the seat journal; measurements live in the readings log; neither is restated "
        "here."
    )
    out.append("")

    out.append("## The answer")
    out.append("")
    out.append(f"- **Unit in flight:** {ans.unit_in_flight}"
               + (f" — {ans.unit_title}" if ans.unit_title else ""))
    out.append(f"- **Next action:** `{ans.next_action}`")
    out.append("- **Blocking unknowns:** "
               + (f"{len(ans.blocking_unknowns)} (below)" if ans.blocking_unknowns else _NONE))
    out.append("")
    if ans.blocking_unknowns:
        out.extend(f"- {b}" for b in ans.blocking_unknowns)
        out.append("")

    out.append("## Units of work")
    out.append("")
    live_rows = [
        f"| {p.id} | {p.status} | {board.plan_phase(p.status)} | {p.title} |"
        for p in sorted(plans, key=lambda p: p.id)
        if p.status in ("in-progress", "ready", "proposed")
    ]
    _table(out, "| plan | status | phase | title |", "|---|---|---|---|", live_rows)
    out.append("")
    tally = " · ".join(f"{st} {sum(1 for p in plans if p.status == st)}"
                       for st in sorted({p.status for p in plans}))
    out.append(f"Status tally: {tally}" if tally else "_(no plans in this scope)_")
    out.append("")

    out.append("## Awaiting the owner")
    out.append("")
    proposed = sorted(p.id for p in plans if p.status == "proposed")
    drafts = sorted(stem for stem, st in notes if st == "draft")
    out.append(f"- bless (proposed→ready): {', '.join(proposed) if proposed else _NONE}")
    out.append(f"- ratify (draft notes): {len(drafts)}"
               + (f" — {', '.join(drafts[:6])}{' …' if len(drafts) > 6 else ''}" if drafts else ""))
    out.append(f"- answer (open owner questions): {len(oqs)}"
               + (f" — {', '.join(o[0] for o in oqs[:8])}{' …' if len(oqs) > 8 else ''}"
                  if oqs else ""))
    out.append("")

    if scope.kind != "plan":
        out.append("## Deskchecks owed")
        out.append("")
        owed = [t for t in board._sorted_tracks(tracks) if board.is_owed(t, dcs)
                and (scope.kind != "track" or t.slug == scope.id)]
        _table(out, "| track | phase |", "|---|---|",
               [f"| {t.lane} | {board.track_phase(t, dcs)} |" for t in owed])
        out.append("")

    out.append("## Open findings")
    out.append("")
    out.append(f"{len(findings)} open"
               + (f" — most recent: {', '.join(sorted(findings)[-6:])}" if findings else ""))
    out.append("")

    out.append("## Readings (MEASURED — latest per command)")
    out.append("")
    readings = latest_per_command(read_readings(seat_dir(root, _seat_of(scope)) / "readings.md"))
    now = datetime.now(UTC) if view.live else None
    _table(out, "| when | command | result |", "|---|---|---|",
           [f"| {_age(ts, now) if now else ts} | `{cmd}` | {res} |" for ts, cmd, res in readings])
    out.append("")

    out.append("## Queue (an input, never the substrate)")
    out.append("")
    for line in (read_queue(root / "data" / "queue.sqlite") if view.live else [QUEUE_POINTER]):
        out.append(f"- {line}")
    out.append("")

    out.append("## The narrative")
    out.append("")
    out.append(
        f"Judgement lives in `docs/roles/{_seat_of(scope)}/journal.md` — read its **authoritative "
        f"segment**: the latest `## CAPSULE — <date>` heading plus every entry above it. This "
        f"rendering deliberately restates none of it."
        if scope.kind == "role" else
        f"This scope has no standing narrative artifact of its own; a `{scope.kind}`'s judgement "
        f"lives in its members' journals. Rendered on demand — nothing was written."
    )
    out.append("")
    out.append("_Derived by `scripts/handoff.py` from artifact front matter + the seat's readings "
               "log. Never hand-edit; edit the sources and regenerate._")
    return "\n".join(out) + "\n"


def _seat_of(scope: Scope) -> str:
    """The seat whose readings/journal a scope renders. Only a role scope owns a seat; the
    orchestrator is the seat that watches everything else."""
    return scope.id if scope.kind == "role" else "orchestrator"


# ── driver ──────────────────────────────────────────────────────
def handoff_text(root: Path, scope: Scope, *, live: bool = False) -> str:
    return render(root, scope, _View(live=live))


def answer_json(root: Path, scope: Scope) -> str:
    """The structured answer — sorted keys, fixed indent, no clock, no sha: byte-identical across
    two invocations over an unchanged tree, exactly like the document it summarizes."""
    return json.dumps(derive(root, scope).as_dict(), indent=2, sort_keys=True,
                      ensure_ascii=False) + "\n"


def _parse(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="handoff.py",
        description="Render the DERIVED handoff for one scope (role | track | plan).")
    g = p.add_mutually_exclusive_group(required=True)
    g.add_argument("--role", metavar="ID", help=f"a seat: {', '.join(ROLE_REGISTRY)}")
    g.add_argument("--track", metavar="SLUG", help="a docs/tracks/<slug>.md manifest")
    g.add_argument("--plan", metavar="ID", help="a docs/build-plans/<id>/plan.md")
    p.add_argument("--write", action="store_true",
                   help="write the role's standing docs/roles/<role>/handoff.md")
    p.add_argument("--check", action="store_true",
                   help="byte-compare a fresh render against the committed file (exit 1 on drift)")
    p.add_argument("--json", action="store_true", dest="as_json",
                   help="emit the structured answer instead of the document")
    return p.parse_args(argv)


def main(argv: list[str]) -> int:
    args = _parse(argv)
    kind, ident = next((k, v) for k, v in
                       (("role", args.role), ("track", args.track), ("plan", args.plan)) if v)
    try:
        scope = resolve(ROOT, kind, ident)
    except ScopeError as exc:
        print(f"handoff: {exc}", file=sys.stderr)
        return 2
    if kind != "role" and (args.write or args.check or args.as_json):
        # §2.9: standing files exist for the role scope only, so there is no fleet of generated
        # files to go unregenerated — and nothing for --check to compare against.
        print(f"handoff: --write/--check/--json apply to --role only; a {kind} scope renders to "
              f"stdout on demand", file=sys.stderr)
        return 2
    if args.as_json:
        sys.stdout.write(answer_json(ROOT, scope))
        return 0
    dest = seat_dir(ROOT, scope.id) / "handoff.md"
    if args.write:
        if not dest.parent.is_dir():
            print(f"handoff: no seat directory {dest.parent.relative_to(ROOT)} — this role has no "
                  f"standing artifacts (note §2.4)", file=sys.stderr)
            return 2
        dest.write_text(handoff_text(ROOT, scope), encoding="utf-8")
        print(f"wrote {dest.relative_to(ROOT)}")
        return 0
    if args.check:
        fresh = handoff_text(ROOT, scope)
        current = dest.read_text(encoding="utf-8") if dest.exists() else None
        if current == fresh:
            print(f"{dest.relative_to(ROOT)}: up to date")
            return 0
        print(f"{dest.relative_to(ROOT)}: STALE — regenerate with "
              f"`uv run scripts/handoff.py --role {scope.id} --write`, then commit. Because the "
              f"rendering embeds no sha and no timestamp, that converges in ONE step.",
              file=sys.stderr)
        return 1
    sys.stdout.write(handoff_text(ROOT, scope, live=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
