# ── GC-1 · the derived causal event poset N = (Ev, ≼), READ-SIDE ONLY ──────────────────────────
# OBJECT:    the spine — a derived index over the audited stores' append events, under the causal
#            order generated by g1 (per-store append chains) ∪ g2 (reads-from references) ∪ g3
#            (recorded program order). dn-global-event-clock §2.1 (GC-N1), §2.2 (generators+audit).
# INVARIANT: read-side derivation, never a write-side sequencer (§2.1-1, the zone-separation
#            argument); metadata-only rows (§2.7 GC-N8 — event id / store / stratum / position /
#            reference ids; NO payload, NO note text, NO observation body — ever); wall-clock is
#            NEVER a generator (Law C4 — no ts/created_at column is read as an ordering key);
#            acyclicity is a construction invariant, not an assumption (§2.8-1, fail-closed).
# ENFORCED:  structural — the spine holds no store write handle (it SELECTs through live read
#            connections and returns data), no model, opens no socket; `derive()` runs a Kahn
#            topological sort and raises `SpineCycleError` on any cycle (a corrupted/forged
#            reference = an integrity failure). Pure-core, ops/derived-tier, ∉ MIRROR_READABLE.
"""The global event clock N as a derived causal spine (GC-1, dn-global-event-clock §2.1–§2.8).

N is the pair `(Ev, ≼)`: all **store-append events** across the audited stores, under the causal
order that is the reflexive-transitive closure of three generator families (note §2.2):

  * **g1 — per-store append chains.** Each store's own append order, where the store records one.
    Ordered by rowid / version_seq — NEVER by a wall timestamp (Law C4: `created_at`/`started_at`/
    `at`/`timestamp` decorate events for display only; they generate no order).
  * **g2 — reads-from (content-address references).** An event whose row records an identifier
    minted by another event is causally after it. This is the attestation auto-link
    (`core/attestation/attestor.py:59-69`, `store.producers_of`) GENERALIZED from attested actions
    to all store events; the attestation DAG embeds as-is (the calibration oracle, §2.8-5).
  * **g3 — recorded program order.** Where one actor's sequence is itself recorded — a run's
    `start_run → add_claim*` (`core/stores/runledger.py`).

**Soundness and incompleteness, stated as a law (note §2.2 — carried verbatim).** Every derived
edge is true (`≼_derived ⊆ ≼_true` — g1 by the single-writer discipline, g2 by content-address
unforgeability, g3 by the recording actor's own order). The converse fails: an unrecorded flow (a
model read a note and influenced a later artifact without a citation) leaves no edge, so **derived
concurrency over-approximates true concurrency**. Every consumer of N inherits this caveat.

Per store, `≼` restricts to a total chain; globally it is a genuine partial order, and that
partiality is a feature (recorded concurrency), not a deficiency (GC-N1).

The audit of what the stores actually record (note §2.2, verified on disk 2026-07-16):

  | store        | g1 chain form                         | how it enters Ev                   |
  |--------------|---------------------------------------|------------------------------------|
  | versions     | per-doc chains by `version_seq`       | g1 (per doc) + produces `digest`   |
  | run ledger   | runs: rowid chain; claims: g3         | g1(runs)+g3(run→claims)+g2(support)|
  | edges        | rowid chain                           | g1 + g2 via `(u, v)` atom digests  |
  | derived      | g2 DAG (`derived_from`) — see below   | g2 only (NO rowid g1 chain)        |
  | attestations | rowid chain PLUS the g2 DAG           | g1 + g2 (`derived_from_ids`/hashes)|
  | eval results | NONE (DuckDB, keyed only)             | chain-less; g2 via key/evidence    |
  | catalog      | NONE (keyed by path)                  | chain-less; produces `digest` (g2) |

**Why the derived store is g2-only (a deliberate, grounded exception).** `DerivedStore.add` uses
`INSERT OR REPLACE`, which REASSIGNS rowid on the idempotent re-write of an artifact. A re-recorded
PARENT can therefore land at a HIGHER rowid than its child, so a rowid g1 chain would contradict
the g2 `derived_from` edge and manufacture a spurious cycle on real (re-run) data. Note §2.2 pins
the derived order as "chain (ties broken by g2, never by wall)": the order IS the `derived_from`
DAG, which is content-id based and store-guaranteed acyclic (`DerivedStore._guard_acyclic`). So the
spine derives NO g1 chain for the derived store; its causal order is entirely g2.

Read-side ONLY: this module derives, and never writes back into, any source store. It holds no
model, opens no socket, and imports no network-capable path (the sealed-core import discipline is
unchanged). The Σ-gated order-query wrapper (GC-N8) is parked — the stratum TAG lands here so the
wrapper needs no re-derivation later; the tag is a per-store library default (see `_STRATUM`).

Not built here (non-goals, per plan §9): clock maps / p_κ / N_s laws (bp-053); cuts (bp-055); the
T-meet completion (bp-056); the Σ-gated query wrapper. This is the spine skeleton and nothing more.
"""

from __future__ import annotations

import hashlib
import json
from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING

# Read-only handles on the audited stores. The spine is "arithmetic over what the stores already
# record" (note §2.1-3, the precedent argument): it SELECTs through their live read connections and
# NEVER writes. Importing these is within the sealed-core import discipline — every one is a
# pure-core (or eval) module with no network path (`ops/import_lint` forbids only edge/cloud/net;
# `core/dreaming/shadow.py` already imports `eval.harness.store`).
from core.attestation.store import AttestationStore
from core.stores.catalog import VaultCatalog
from core.stores.derived import DerivedStore
from core.stores.edges import EdgeStore
from core.stores.runledger import RunLedger
from core.stores.versions import VersionStore
from eval.harness.store import EvalResultsStore

if TYPE_CHECKING:
    from config.loader import Config


# ═══════════════════════════════════════════════════════════════════════════════════════════════
# Public surface (pinned — plan §6; GC-2/GC-3 EXTEND this, never reshape it)
# ═══════════════════════════════════════════════════════════════════════════════════════════════


@dataclass(frozen=True)
class SpineEvent:
    """One store-append event. METADATA ONLY (§2.7 GC-N8): no payload, no note text, no observation
    body — content digests / run_ids / SHAs are IDENTIFIERS here, never dereferenced to text."""

    event_id: str          # "<store>:<chain-key>:<position>" — deterministic, content-free
    store: str
    stratum: str           # the Σ tag (mirror/ops/interpreted/eval — the note's visibility rule)
    position: int | None   # None for chain-less (eval / catalog) events
    refs: tuple[str, ...]  # outbound content-address identifiers (digests, run_ids, SHAs)


class Order(Enum):
    BEFORE = "before"
    AFTER = "after"
    CONCURRENT = "concurrent"


@dataclass(frozen=True)
class SpineEdge:
    """One DIRECT generator edge (pre-closure), tagged by its family. Exposed via `generators()`
    so GC-2/GC-3 and the §2.8-5 calibration can inspect the edges ≼ is the closure of."""

    src: str
    dst: str
    gen: str               # "g1" | "g2" | "g3"


@dataclass(frozen=True)
class SpineReport:
    """The no-silent-caps report (§2.9-5): what was enumerated, and — NAMED, never silently absent —
    the stores beyond the core seven that this skeleton does not yet wire."""

    stores_enumerated: tuple[str, ...]     # the wired stores whose source handle was present
    event_count: int
    edge_count: int                        # distinct direct (src, dst) adjacency pairs
    chainless_stores: tuple[str, ...]      # stores with position=None events (eval / catalog)
    # refs that resolved to no producing event — DROPPED, never fabricated into an edge (Item 2
    # falsifier). Expected > 0: corpus_digest / config_fingerprint / spec_hash have no minter.
    refs_without_producer: int
    stores_unwired: tuple[str, ...]        # beyond the §2.2 seven — parked, named (plan §11)


class SpineCycleError(RuntimeError):
    """A cycle in `≼_derived` — a corrupted/forged reference or a generator bug (§2.8-1). Acyclicity
    is an INVARIANT, not an assumption: content-address unforgeability makes every honest reference
    point backward in true time, so a cycle is an integrity failure and `derive()` fails CLOSED."""


# Beyond the §2.2 core seven — the note §2.9-5 enumerates these as chain-carrying (SQLite) or
# chain-less (DuckDB) but they are NOT wired by GC-1 (parked, plan §11: re-entry = GC-2 needs their
# clocks). Named here so a store is never SILENTLY absent from the spine's report.
_UNWIRED_STORES: tuple[str, ...] = ("proposals", "verdicts", "observations", "telemetry")

# The per-store Σ tag (§2.7 vocabulary; `core/scope.py` Stratum forest). A library-level DEFAULT:
# the note under-specifies the exact per-store mapping (the Σ-gated View wrapper is parked, plan
# §11), so this is a documented default, refinable by the View layer without re-deriving the spine.
# eval keeps its OWN Σ (§2.9-1: its own stratum, non-promotable, ∉ MIRROR_READABLE).
_STRATUM: dict[str, str] = {
    "versions": "mirror",
    "catalog": "mirror",
    "edges": "interpreted",
    "derived": "interpreted",
    "runledger": "ops",
    "attestations": "ops",
    "eval": "eval",
}


def _event_id(store: str, chain_key: str, position: int | None) -> str:
    """Deterministic, content-free event id. Chain-less events render position as '-'."""
    return f"{store}:{chain_key}:{position if position is not None else '-'}"


# ═══════════════════════════════════════════════════════════════════════════════════════════════
# Injectable sources (plan §6: "a small dataclass of optional store handles … every one injectable")
# ═══════════════════════════════════════════════════════════════════════════════════════════════


@dataclass
class SpineSources:
    """Optional handles on the audited stores. Tests inject fakes (in-memory stores seeded with
    controlled data); production resolves from config lazily (`resolve()`, the shadow-runner seam
    pattern). A None handle = that store is simply not part of this derivation."""

    ledger: RunLedger | None = None
    versions: VersionStore | None = None
    edges: EdgeStore | None = None
    derived: DerivedStore | None = None
    attestations: AttestationStore | None = None
    eval: EvalResultsStore | None = None
    catalog: VaultCatalog | None = None

    @classmethod
    def resolve(cls, config: Config | None = None) -> SpineSources:
        """Open each audited store from config — but ONLY where its file already exists, so the
        resolver has no side effects (never creates an empty DB). A store whose DuckDB file is
        write-locked (a running daemon) is skipped rather than raising; it surfaces as absent from
        the report's `stores_enumerated` (honest, no silent cap)."""
        from config.loader import get_config

        cfg = config or get_config()
        base = cfg.paths.derived_store.parent
        versions_p = base / "versions.sqlite"
        ledger_p = base / "run_ledger.sqlite"
        edges_p = base / "edges.sqlite"
        eval_p = base / "eval_results.duckdb"

        eval_src: EvalResultsStore | None = None
        if eval_p.exists():
            try:
                eval_src = EvalResultsStore(eval_p)
            except Exception:  # resilience guard: a write-locked DuckDB is skipped, never fatal
                eval_src = None

        return cls(
            versions=VersionStore(versions_p) if versions_p.exists() else None,
            ledger=RunLedger(ledger_p) if ledger_p.exists() else None,
            edges=EdgeStore(edges_p) if edges_p.exists() else None,
            derived=(
                DerivedStore(cfg.paths.derived_store)
                if cfg.paths.derived_store.exists() else None
            ),
            attestations=(
                AttestationStore(cfg.paths.attestation_store)
                if cfg.paths.attestation_store.exists() else None
            ),
            eval=eval_src,
            catalog=(
                VaultCatalog(cfg.paths.vault_catalog)
                if cfg.paths.vault_catalog.exists() else None
            ),
        )


# ═══════════════════════════════════════════════════════════════════════════════════════════════
# The builder — enumeration + generator edges (kept off the public Spine)
# ═══════════════════════════════════════════════════════════════════════════════════════════════


@dataclass
class _Builder:
    """Accumulates events, the produced-by index, and g1/g3 direct edges as each store is
    enumerated; `finalize()` computes g2 and enforces acyclicity."""

    events: dict[str, SpineEvent] = field(default_factory=dict)
    chain_of: dict[str, str] = field(default_factory=dict)          # event_id -> frontier key
    produced_by: dict[str, set[str]] = field(default_factory=dict)  # identifier -> minting events
    consumes: dict[str, tuple[str, ...]] = field(default_factory=dict)  # event_id -> refs it reads
    g13_edges: set[tuple[str, str, str]] = field(default_factory=set)   # (src, dst, gen) g1|g3
    present: list[str] = field(default_factory=list)

    def _add(self, store: str, chain_key: str, position: int | None,
             produces: tuple[str, ...], consumes: tuple[str, ...]) -> str:
        eid = _event_id(store, chain_key, position)
        refs = tuple(sorted(set(produces) | set(consumes)))
        self.events[eid] = SpineEvent(event_id=eid, store=store, stratum=_STRATUM[store],
                                      position=position, refs=refs)
        self.chain_of[eid] = f"{store}:{chain_key}"
        for p in produces:
            self.produced_by.setdefault(p, set()).add(eid)
        self.consumes[eid] = consumes
        return eid

    # -- g1 per-store append chains + the per-event produce/consume identifiers --------------------
    def versions(self, store: VersionStore) -> None:
        self.present.append("versions")
        prev_by_doc: dict[str, str] = {}
        rows = store._conn.execute(
            "SELECT doc_id, version_seq, digest FROM versions ORDER BY doc_id, version_seq"
        ).fetchall()
        for row in rows:
            doc_id, seq, digest = str(row["doc_id"]), int(row["version_seq"]), str(row["digest"])
            eid = self._add("versions", doc_id, seq, produces=(digest,), consumes=())
            prev = prev_by_doc.get(doc_id)
            if prev is not None:                              # per-doc chain (the op-seq exemplar)
                self.g13_edges.add((prev, eid, "g1"))
            prev_by_doc[doc_id] = eid

    def ledger(self, store: RunLedger) -> None:
        self.present.append("runledger")
        run_event: dict[str, str] = {}
        prev_run: str | None = None
        for row in store._conn.execute(
            "SELECT rowid, run_id, config_fingerprint, corpus_digest FROM dream_runs ORDER BY rowid"
        ).fetchall():
            rid, pos = str(row["run_id"]), int(row["rowid"])
            cf, cd = str(row["config_fingerprint"]), str(row["corpus_digest"])
            eid = self._add("runledger", "run", pos, produces=(rid,), consumes=(cf, cd))
            if prev_run is not None:                          # g1 run chain (rowid, not started_at)
                self.g13_edges.add((prev_run, eid, "g1"))
            prev_run, run_event[rid] = eid, eid
        last_claim: dict[str, str] = {}
        for row in store._conn.execute(
            "SELECT rowid, claim_id, run_id, support_json FROM dream_claims ORDER BY rowid"
        ).fetchall():
            cid, pos, rid = str(row["claim_id"]), int(row["rowid"]), str(row["run_id"])
            support = tuple(str(x) for x in json.loads(row["support_json"]))
            eid = self._add("runledger", "claim", pos, produces=(cid,), consumes=support)
            prior = last_claim.get(rid)                       # g3 recorded program order:
            if prior is not None:                             #   run → claim_1 → claim_2 → …
                self.g13_edges.add((prior, eid, "g3"))
            elif rid in run_event:
                self.g13_edges.add((run_event[rid], eid, "g3"))
            last_claim[rid] = eid

    def edges(self, store: EdgeStore) -> None:
        self.present.append("edges")
        prev: str | None = None
        for row in store._conn.execute(
            "SELECT rowid, edge_id, u, v FROM edges ORDER BY rowid"
        ).fetchall():
            edge_id, pos = str(row["edge_id"]), int(row["rowid"])
            u, v = str(row["u"]), str(row["v"])
            eid = self._add("edges", "edges", pos, produces=(edge_id,), consumes=(u, v))
            if prev is not None:                              # g1 append chain (rowid)
                self.g13_edges.add((prev, eid, "g1"))
            prev = eid

    def derived(self, store: DerivedStore) -> None:
        self.present.append("derived")
        rows = store._conn.execute(
            "SELECT rowid, id, derived_from, attestation_id "
            "FROM interpreted_artifacts ORDER BY rowid"
        ).fetchall()
        for row in rows:
            aid, pos = str(row["id"]), int(row["rowid"])
            df = tuple(str(x) for x in json.loads(row["derived_from"] or "[]"))
            att = row["attestation_id"]
            consumes = df + ((str(att),) if att is not None else ())
            # NO g1 rowid edge: the derived order IS the g2 `derived_from` DAG (module docstring;
            # §2.2 "ties broken by g2, never by wall" — INSERT OR REPLACE reassigns rowid).
            self._add("derived", "derived", pos, produces=(aid,), consumes=consumes)

    def attestations(self, store: AttestationStore) -> None:
        self.present.append("attestations")
        records = {a.id: a for a in store.all()}              # typed records; order irrelevant here
        prev: str | None = None
        for row in store._conn.execute(
            "SELECT rowid, id FROM attestations ORDER BY rowid"  # g1 append order = rowid (stable)
        ).fetchall():
            aid, pos = str(row["id"]), int(row["rowid"])
            rec = records.get(aid)
            if rec is None:
                produces: tuple[str, ...] = (aid,)
                consumes: tuple[str, ...] = ()
            else:
                # produces its id + outputs; consumes its inputs + parent ids (auto-link, §2.8-5)
                produces = (aid, *rec.output_hashes)
                consumes = (*rec.input_hashes, *rec.derived_from_ids)
            eid = self._add("attestations", "attestation", pos,
                            produces=produces, consumes=consumes)
            if prev is not None:
                self.g13_edges.add((prev, eid, "g1"))
            prev = eid

    def eval(self, store: EvalResultsStore) -> None:
        self.present.append("eval")
        for r in store.query():                               # chain-less: position=None, g2 only
            k = r.key
            chain_key = hashlib.sha256(
                "\x00".join([k.spec_hash, k.corpus_ref, k.config_fingerprint,
                             str(k.seed), r.metric_name]).encode("utf-8")
            ).hexdigest()[:16]
            cons = [k.corpus_ref, k.config_fingerprint, k.spec_hash]
            if r.evidence_ref is not None:
                cons.append(r.evidence_ref)                   # may resolve to an attestation id
            self._add("eval", chain_key, None, produces=(), consumes=tuple(cons))

    def catalog(self, store: VaultCatalog) -> None:
        self.present.append("catalog")
        for row in store._conn.execute(
            "SELECT source_path, digest FROM vault_files ORDER BY source_path"  # keyed by path
        ).fetchall():
            sp, digest = str(row["source_path"]), str(row["digest"])
            # chain-less; produces its content digest (downstream consumers order after it)
            self._add("catalog", sp, None, produces=(digest,), consumes=())

    # -- g2 (reads-from) + acyclicity → the immutable Spine ---------------------------------------
    def finalize(self) -> Spine:
        gen: set[tuple[str, str, str]] = set(self.g13_edges)
        refs_without_producer = 0
        for eid, refs in self.consumes.items():
            for ident in refs:
                producers = self.produced_by.get(ident)
                if not producers:                             # a ref no enumerated event minted —
                    refs_without_producer += 1                #   DROPPED, never fabricated (Item 2)
                    continue
                for p in producers:                           # generalized `producers_of`: p → e
                    if p != eid:
                        gen.add((p, eid, "g2"))

        succ: dict[str, set[str]] = {e: set() for e in self.events}
        for src, dst, _g in gen:
            succ[src].add(dst)
        _assert_acyclic(succ)                                 # construction invariant (§2.8-1)

        gen_edges = tuple(SpineEdge(src=s, dst=d, gen=g) for s, d, g in sorted(gen))
        return Spine(
            _events=dict(self.events),
            _succ=succ,
            _chain_of=dict(self.chain_of),
            _gen_edges=gen_edges,
            _produced_by={k: set(v) for k, v in self.produced_by.items()},
            _present=tuple(self.present),
            _refs_without_producer=refs_without_producer,
        )


def _assert_acyclic(succ: dict[str, set[str]]) -> None:
    """Kahn topological sort; raise if not every node is processed (a cycle remains). Fail-closed —
    a cycle in `≼_derived` is a corrupted/forged reference, not a design problem (plan §10)."""
    indeg: dict[str, int] = dict.fromkeys(succ, 0)
    for outs in succ.values():
        for m in outs:
            indeg[m] += 1
    ready = deque(n for n, d in indeg.items() if d == 0)
    processed = 0
    while ready:
        n = ready.popleft()
        processed += 1
        for m in succ[n]:
            indeg[m] -= 1
            if indeg[m] == 0:
                ready.append(m)
    if processed != len(succ):
        cycle = sorted(n for n, d in indeg.items() if d > 0)
        raise SpineCycleError(
            f"cycle in ≼_derived over {len(cycle)} events — a corrupted/forged reference "
            f"(§2.8-1, fail-closed): {cycle[:8]}"
        )


# ═══════════════════════════════════════════════════════════════════════════════════════════════
# The spine
# ═══════════════════════════════════════════════════════════════════════════════════════════════


@dataclass
class Spine:
    """The derived causal event poset `(Ev, ≼)`. Construct via `derive()`; `≼` is the reflexive-
    transitive closure of the g1 ∪ g2 ∪ g3 generator edges (`generators()`)."""

    _events: dict[str, SpineEvent]
    _succ: dict[str, set[str]]                    # direct adjacency (g1∪g2∪g3); closure on restrict
    _chain_of: dict[str, str]                     # event_id -> "<store>:<chain-key>" frontier key
    _gen_edges: tuple[SpineEdge, ...]             # direct generator edges, sorted (deterministic)
    _produced_by: dict[str, set[str]]             # identifier -> minting event_ids
    _present: tuple[str, ...]
    _refs_without_producer: int

    @classmethod
    def derive(cls, sources: SpineSources) -> Spine:
        """Enumerate the present stores and build `(Ev, ≼)`. Raises `SpineCycleError` if the derived
        order is not acyclic (an integrity failure — plan §10 STOP-and-raise)."""
        b = _Builder()
        if sources.versions is not None:
            b.versions(sources.versions)
        if sources.ledger is not None:
            b.ledger(sources.ledger)
        if sources.edges is not None:
            b.edges(sources.edges)
        if sources.derived is not None:
            b.derived(sources.derived)
        if sources.attestations is not None:
            b.attestations(sources.attestations)
        if sources.eval is not None:
            b.eval(sources.eval)
        if sources.catalog is not None:
            b.catalog(sources.catalog)
        return b.finalize()

    # -- the pinned surface ------------------------------------------------------------------------
    def order(self, a: str, b: str) -> Order:
        """`order(e, e′) ∈ {before, after, concurrent}` over the transitive closure of ≼. An event
        is CONCURRENT with itself (≺ is irreflexive) and with any event neither reaches."""
        if a not in self._events:
            raise KeyError(f"unknown event {a!r}")
        if b not in self._events:
            raise KeyError(f"unknown event {b!r}")
        if a == b:
            return Order.CONCURRENT
        if b in self._reachable(a):
            return Order.BEFORE
        if a in self._reachable(b):
            return Order.AFTER
        return Order.CONCURRENT

    def frontier(self) -> dict[str, int]:
        """Per-chain latest positions — the vector of per-store chain positions a cut is read at
        (note §2.4). Keyed by "<store>:<chain-key>" (per-doc for versions); chain-less events
        (position=None) do not contribute."""
        out: dict[str, int] = {}
        for eid, ev in self._events.items():
            if ev.position is None:
                continue
            key = self._chain_of[eid]
            if key not in out or ev.position > out[key]:
                out[key] = ev.position
        return out

    def restrict(self, stratum: str) -> Spine:
        """N_s — the restriction of `(Ev, ≼)` to stratum-s events (the induced sub-poset: a ≼_s b
        iff a ≼ b in N and both events are in s). GC-2 consumes this."""
        kept = {eid for eid, ev in self._events.items() if ev.stratum == stratum}
        new_succ = {e: (self._reachable(e) & kept) for e in kept}   # induced transitive closure
        new_pb = {i: (evs & kept) for i, evs in self._produced_by.items() if evs & kept}
        return Spine(
            _events={e: self._events[e] for e in kept},
            _succ=new_succ,
            _chain_of={e: self._chain_of[e] for e in kept},
            _gen_edges=tuple(ed for ed in self._gen_edges if ed.src in kept and ed.dst in kept),
            _produced_by=new_pb,
            _present=self._present,
            _refs_without_producer=0,
        )

    def events(self) -> list[SpineEvent]:
        """Every event, in deterministic event_id order."""
        return [self._events[e] for e in sorted(self._events)]

    # -- extensions (GC-2/GC-3 + the §2.8-5 calibration) -------------------------------------------
    def generators(self) -> tuple[SpineEdge, ...]:
        """The DIRECT generator edges (g1/g2/g3), tagged — the edges ≼ is the closure of. The g2
        subset restricted to attestation events is the calibration oracle (§2.8-5)."""
        return self._gen_edges

    def producers_of(self, idents: set[str]) -> set[str]:
        """Generalizes `AttestationStore.producers_of` from attested actions to ALL store events:
        the event_ids whose produced identifiers intersect `idents` (the g2 generator, §2.2)."""
        out: set[str] = set()
        for i in idents:
            out |= self._produced_by.get(i, set())
        return out

    def report(self) -> SpineReport:
        """The no-silent-caps report (§2.9-5): enumerated stores, chain-less stores, and the stores
        beyond the §2.2 seven that this skeleton leaves unwired — NAMED, never silently absent."""
        chainless = tuple(sorted({ev.store for ev in self._events.values() if ev.position is None}))
        return SpineReport(
            stores_enumerated=self._present,
            event_count=len(self._events),
            edge_count=sum(len(s) for s in self._succ.values()),
            chainless_stores=chainless,
            refs_without_producer=self._refs_without_producer,
            stores_unwired=_UNWIRED_STORES,
        )

    # -- internal ----------------------------------------------------------------------------------
    def _reachable(self, start: str) -> set[str]:
        """Every event strictly reachable from `start` over the direct adjacency (BFS)."""
        seen: set[str] = set()
        queue = deque(self._succ.get(start, set()))
        while queue:
            n = queue.popleft()
            if n in seen:
                continue
            seen.add(n)
            queue.extend(self._succ.get(n, set()))
        return seen
