# ── GC-1 · the derived causal event poset N = (Ev, ≼), READ-SIDE ONLY ──────────────────────────
# OBJECT:    the spine — a derived index over the audited stores' append events, under the causal
#            order generated by g1 (per-store append chains) ∪ g2 (reads-from references) ∪ g3
#            (recorded program order). dn-global-event-clock §2.1 (GC-N1), §2.2 (generators+audit).
# INVARIANT: read-side derivation, never a write-side sequencer (§2.1-1, the zone-separation
#            argument); metadata-only rows (§2.7 GC-N8 — event id / store / stratum / position /
#            reference ids; NO payload, NO note text, NO observation body — ever); wall-clock is
#            NEVER a generator (Law C4 — no ts/created_at column is read as an ordering key);
#            acyclicity is a construction invariant, not an assumption (§2.8-1, fail-closed).
# ENFORCED:  structural — the spine holds no store write handle (it SELECTs through live read
#            connections and returns data), no model, opens no socket; `derive()` runs a Kahn
#            topological sort and raises `SpineCycleError` on any cycle (a corrupted/forged
#            reference = an integrity failure). Pure-core, ops/derived-tier, ∉ MIRROR_READABLE.
"""The global event clock N as a derived causal spine (GC-1, dn-global-event-clock §2.1–§2.8).

N is the pair `(Ev, ≼)`: all **store-append events** across the audited stores, under the causal
order that is the reflexive-transitive closure of three generator families (note §2.2):

  * **g1 — per-store append chains.** Each store's own append order, where the store records one.
    Ordered by rowid / version_seq — NEVER by a wall timestamp (Law C4: `created_at`/`started_at`/
    `at`/`timestamp` decorate events for display only; they generate no order).
  * **g2 — reads-from (content-address references).** An event whose row records an identifier
    MINTED by another event is causally after it. This is the attestation auto-link
    (`core/attestation/attestor.py:59-69`, `store.producers_of`) GENERALIZED from attested actions
    to all store events; the attestation DAG embeds as-is (the calibration oracle, §2.8-5).
    Faithfully implementing §2.8-5: an attestation is a proof-layer record, NOT the minter of its
    outputs (each output is written to a store, whose OWN event mints it), so attestation→
    attestation order is exactly the `derived_from_ids` DAG — never the raw output/input hash
    coincidence, which over-generates on a SHARED corpus/config digest (mutable state listed as
    both an input and an output of many attestations) and would manufacture a false cycle.
  * **g3 — recorded program order.** Where one actor's sequence is itself recorded — a run's
    `start_run → add_claim*` (`core/stores/runledger.py`).

**Soundness and incompleteness, stated as a law (note §2.2 — carried verbatim).** Every derived
edge is true (`≼_derived ⊆ ≼_true` — g1 by the single-writer discipline, g2 by content-address
unforgeability, g3 by the recording actor's own order). The converse fails: an unrecorded flow (a
model read a note and influenced a later artifact without a citation) leaves no edge, so **derived
concurrency over-approximates true concurrency**. Every consumer of N inherits this caveat.

Per store, `≼` restricts to a total chain; globally it is a genuine partial order, and that
partiality is a feature (recorded concurrency), not a deficiency (GC-N1).

The audit of what the stores actually record (note §2.2, verified on disk 2026-07-16):

  | store        | g1 chain form                         | how it enters Ev                   |
  |--------------|---------------------------------------|------------------------------------|
  | versions     | per-doc chains by `version_seq`       | g1 (per doc) + produces `digest`   |
  | run ledger   | runs: rowid chain; claims: g3         | g1(runs)+g3(run→claims)+g2(support)|
  | edges        | rowid chain                           | g1 + g2 via `(u, v)` atom digests  |
  | derived      | g2 DAG (`derived_from`) — see below   | g2 only (NO rowid g1 chain)        |
  | attestations | rowid chain PLUS the g2 DAG           | g1 + g2 (`derived_from_ids`/hashes)|
  | eval results | NONE (DuckDB, keyed only)             | chain-less; g2 via key/evidence    |
  | catalog      | NONE (keyed by path)                  | chain-less; produces `digest` (g2) |

**Why the derived store is g2-only (a deliberate, grounded exception).** `DerivedStore.add` uses
`INSERT OR REPLACE`, which REASSIGNS rowid on the idempotent re-write of an artifact. A re-recorded
PARENT can therefore land at a HIGHER rowid than its child, so a rowid g1 chain would contradict
the g2 `derived_from` edge and manufacture a spurious cycle on real (re-run) data. Note §2.2 pins
the derived order as "chain (ties broken by g2, never by wall)": the order IS the `derived_from`
DAG, which is content-id based and store-guaranteed acyclic (`DerivedStore._guard_acyclic`). So the
spine derives NO g1 chain for the derived store; its causal order is entirely g2.

Read-side ONLY: this module derives, and never writes back into, any source store. It holds no
model, opens no socket, and imports no network-capable path (the sealed-core import discipline is
unchanged). The Σ-gated order-query wrapper (GC-N8) is parked — the stratum TAG lands here so the
wrapper needs no re-derivation later; the tag is a per-store library default (see `_STRATUM`).

Not built here (non-goals, per plan §9): clock maps / p_κ / N_s laws (bp-053); cuts (bp-055); the
T-meet completion (bp-056); the Σ-gated query wrapper. This is the spine skeleton and nothing more.
"""

from __future__ import annotations

import hashlib
import json
from collections import deque
from collections.abc import Hashable
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import TYPE_CHECKING

# Read-only handles on the audited stores. The spine is "arithmetic over what the stores already
# record" (note §2.1-3, the precedent argument): it SELECTs through their live read connections and
# NEVER writes. Importing these is within the sealed-core import discipline — every one is a
# pure-core (or eval) module with no network path (`ops/import_lint` forbids only edge/cloud/net;
# `core/dreaming/shadow.py` already imports `eval.harness.store`).
from core.attestation.store import AttestationStore

# `Clock` is READ-ONLY vocabulary here (the registered clock hierarchy); bp-056 owns changes to it.
from core.scope import Clock
from core.stores.catalog import VaultCatalog
from core.stores.derived import DerivedStore
from core.stores.edges import EdgeStore
from core.stores.runledger import RunLedger
from core.stores.versions import VersionStore
from eval.harness.store import EvalResultsStore

if TYPE_CHECKING:
    from config.loader import Config


# ═══════════════════════════════════════════════════════════════════════════════════════════════
# Public surface (pinned — plan §6; GC-2/GC-3 EXTEND this, never reshape it)
# ═══════════════════════════════════════════════════════════════════════════════════════════════


@dataclass(frozen=True)
class SpineEvent:
    """One store-append event. METADATA ONLY (§2.7 GC-N8): no payload, no note text, no observation
    body — content digests / run_ids / SHAs are IDENTIFIERS here, never dereferenced to text."""

    event_id: str          # "<store>:<chain-key>:<position>" — deterministic, content-free
    store: str
    stratum: str           # the Σ tag (mirror/ops/interpreted/eval — the note's visibility rule)
    position: int | None   # None for chain-less (eval / catalog) events
    refs: tuple[str, ...]  # outbound content-address identifiers (digests, run_ids, SHAs)


class Order(Enum):
    BEFORE = "before"
    AFTER = "after"
    CONCURRENT = "concurrent"


@dataclass(frozen=True)
class SpineEdge:
    """One DIRECT generator edge (pre-closure), tagged by its family. Exposed via `generators()`
    so GC-2/GC-3 and the §2.8-5 calibration can inspect the edges ≼ is the closure of."""

    src: str
    dst: str
    gen: str               # "g1" | "g2" | "g3"


@dataclass(frozen=True)
class SpineReport:
    """The no-silent-caps report (§2.9-5): what was enumerated, and — NAMED, never silently absent —
    the stores beyond the core seven that this skeleton does not yet wire."""

    stores_enumerated: tuple[str, ...]     # the wired stores whose source handle was present
    event_count: int
    edge_count: int                        # distinct direct (src, dst) adjacency pairs
    chainless_stores: tuple[str, ...]      # stores with position=None events (eval / catalog)
    # refs that resolved to no producing event — DROPPED, never fabricated into an edge (Item 2
    # falsifier). Expected > 0: corpus_digest / config_fingerprint / spec_hash have no minter.
    refs_without_producer: int
    stores_unwired: tuple[str, ...]        # beyond the §2.2 seven — parked, named (plan §11)


class SpineCycleError(RuntimeError):
    """A cycle in `≼_derived` — a corrupted/forged reference or a generator bug (§2.8-1). Acyclicity
    is an INVARIANT, not an assumption: content-address unforgeability makes every honest reference
    point backward in true time, so a cycle is an integrity failure and `derive()` fails CLOSED."""


# ── GC-3 · certified quiescent cuts (plan §6; note §2.4 GC-N3 — the SLICE rule completed) ─────────
# A cut is a DOWN-SET of (Ev, ≼): a per-chain frontier vector PLUS a certificate that makes it sound
# despite the incompleteness law (`≼_derived ⊆ ≼_true`, §2.2) — a computed-but-uncertified cut is
# REFUSED, never warned. Each certificate comes from ONE named observable, never wall-time or
# inference (the plan §7 falsifier: a certificate asserted from anything but its observable):
#   * COMMIT   — the repo snapshot is atomic (git); certifies repo-backed strata. Evidence is a
#                commit SHA — INJECTED (core never shells to git, §2.10), never sourced here.
#   * TROUGH   — the scheduler owns the job queue (single-writer, runledger:16-18); an empty queue
#                between trough jobs certifies no in-flight core causality. Evidence is the
#                scheduler's OWN quiescence fact (`TroughState`, built by the caller from
#                `scheduler.JobQueue.counts()`) — core cannot IMPORT scheduler (scheduler imports
#                core; a handle would cycle), so the FACT is injected, never fabricated.
#   * HANDOFF  — the sensing handoff's requests/ and observations/ dirs empty (core/sensing.py:236)
#                certify no in-flight edge↔core flow. Evidence is a hash of the (empty) listing; the
#                spine lists the dir (a filesystem read — no socket, no vault, no network).


class Certificate(Enum):
    """The quiescence certificate a cut carries (note §2.4 GC-N3). A cross-strata cut COMPOSES all
    certificates its strata require; a missing certificate for an in-scope stratum ⇒ REFUSAL."""

    COMMIT = "commit"
    TROUGH = "trough-quiescent"
    HANDOFF = "handoff-empty"


class CutCertificateError(ValueError):
    """A cut was requested but a required certificate could not be SOURCED from its named observable
    (no injection, or the observable reports NOT quiescent). The cut REFUSES construction with a
    clear message rather than fabricate a certificate (plan §7 falsifier; note §2.4)."""


@dataclass(frozen=True)
class TroughState:
    """The scheduler's OWN quiescence fact, injected (core cannot import scheduler — a cycle).
    The caller reads `scheduler.JobQueue.counts()` and builds this; `quiescent` iff no QUEUED and no
    RUNNING jobs (an empty queue BETWEEN trough jobs, note §2.4-2). `trough_id` is the evidence — a
    marker of WHICH quiescent state (a queue-state id / done-count, NEVER a wall timestamp)."""

    queued: int
    running: int
    trough_id: str

    @property
    def quiescent(self) -> bool:
        return self.queued == 0 and self.running == 0


@dataclass(frozen=True)
class CutSources:
    """The injected certificate observables `cut_at` sources from. Every field optional; a cut whose
    strata require a certificate with no source here REFUSES (never fabricates). Kept OFF `derive`'s
    store enumeration (`SpineSources`) — these are cut-time facts, not the append handles."""

    commit_sha: str | None = None       # the atomic repo snapshot SHA (injected; no git-shell)
    trough: TroughState | None = None   # the scheduler's own quiescence fact (JobQueue.counts())
    handoff: Path | None = None         # the sensing handoff dir (requests/ + observations/)


@dataclass(frozen=True)
class CertifiedCut:
    """A certified consistent cut (note §2.4 GC-N3): a per-chain frontier vector + the certificates
    that make it sound + their evidence. HASHABLE — it rides UNCHANGED in `Scope.cut` (the opaque
    `Hashable` field; the plan pin keeps `core/scope.py` untouched).

    `frontier` is `sorted (chain-key, position)` pairs, where chain-key is `"<store>:<chain-key>"`
    exactly as `Spine.frontier()` keys it (per-DOC for versions — collapsing to a bare store would
    lose the per-doc soundness the down-set needs). The pin's "(store, position)" reads chain-key as
    the str; the pinned TYPE `tuple[tuple[str, int], ...]` is honored verbatim."""

    frontier: tuple[tuple[str, int], ...]
    certificates: frozenset[Certificate]
    evidence: tuple[str, ...]


# Beyond the §2.2 core seven — the note §2.9-5 enumerates these as chain-carrying (SQLite) or
# chain-less (DuckDB) but they are NOT wired by GC-1 (parked, plan §11: re-entry = GC-2 needs their
# clocks). Named here so a store is never SILENTLY absent from the spine's report.
_UNWIRED_STORES: tuple[str, ...] = ("proposals", "verdicts", "observations", "telemetry")

# The per-store Σ tag (§2.7 vocabulary; `core/scope.py` Stratum forest). A library-level DEFAULT:
# the note under-specifies the exact per-store mapping (the Σ-gated View wrapper is parked, plan
# §11), so this is a documented default, refinable by the View layer without re-deriving the spine.
# eval keeps its OWN Σ (§2.9-1: its own stratum, non-promotable, ∉ MIRROR_READABLE).
_STRATUM: dict[str, str] = {
    "versions": "mirror",
    "catalog": "mirror",
    "edges": "interpreted",
    "derived": "interpreted",
    "runledger": "ops",
    "attestations": "ops",
    "eval": "eval",
}

# The certificate(s) each stratum requires for a cut to be sound (note §2.4; plan §8 "certificates
# for all strata whose stores intersect the frontier"). GROUNDED, a spec-fidelity resolution the
# note under-specifies as an exact map (finding-0095):
#   * mirror (versions/catalog = the repo-backed corpus) → COMMIT — the ratified `_CUT_CLOCKS` case:
#     the commit SHA IS the cut for repo-backed strata (`core/scope.py:450`).
#   * ops (runledger/attestations) + interpreted (edges/derived) = core stores written by scheduler
#     jobs that can incorporate in-flight edge observations → TROUGH (no in-flight core causality)
#     AND HANDOFF (no in-flight edge↔core flow). A cut across the core↔edge boundary needs both.
#   * eval (eval results) = internal scheduler jobs, no edge dependency → TROUGH.
# The FULL cross-strata cut (all four) therefore composes {COMMIT, TROUGH, HANDOFF} — exactly the
# note's "commit ∧ trough-empty ∧ handoff-empty" (§2.4).
_STRATUM_CERTIFICATES: dict[str, frozenset[Certificate]] = {
    "mirror": frozenset({Certificate.COMMIT}),
    "ops": frozenset({Certificate.TROUGH, Certificate.HANDOFF}),
    "interpreted": frozenset({Certificate.TROUGH, Certificate.HANDOFF}),
    "eval": frozenset({Certificate.TROUGH}),
}

# The handoff-empty observable — MIRRORED (not imported) from `core/sensing.py:63-64`, the zone-
# boundary discipline: the sealed core and the edge share "nothing but the async file handoff …
# mirrored-not-imported wire shapes" (note §2.1-1). Both dirs empty ⇒ no in-flight edge↔core flow.
_HANDOFF_SUBDIRS: tuple[str, ...] = ("requests", "observations")


def _event_id(store: str, chain_key: str, position: int | None) -> str:
    """Deterministic, content-free event id. Chain-less events render position as '-'."""
    return f"{store}:{chain_key}:{position if position is not None else '-'}"


# ── GC-2 · the clock maps (plan §6; note §2.3 laws C1–C4) ────────────────────────────────────────
# The registered clocks (`core/scope.py:171-184`, READ-ONLY here) partition by how their p_κ is
# sourced against the materialized spine (= N):
#   * N              — identity: p_N(e) = e (the finest clock, the spine itself). Singleton fibers.
#   * N_S            — per-stratum event tick: p(N_S, e) = (stratum, e). The RICH N_s object (the
#                      restriction with its induced order + proper time) is `Spine.n_s(stratum)`.
#   * read-clocks    — projection_event / last_write / now: mint NO events; their tick is the
#                      BORROWED per-store frontier (Law C3). p(read,e) = frontier_at(e.store).
#   * WALL           — Law C4: generates nothing; p/fiber RAISE. No p_wall exists (structural).
#   * COMMIT /       — repo-backed COARSENINGS ("a commit is a RANGE of N"). Their tick is which git
#     DISTINCT_       commit / content-snapshot an event belongs to — sourced EXTERNALLY: no store
#     SNAPSHOT        spine enumerates carries a commit SHA, and `core/` never shells to git (§2.10:
#                     the spine is arithmetic over stores, opens no socket). So the tick is INJECTED
#                     (`coarsening_ticks`), and p/fiber over the injected map; absent it, p RAISES a
#                     clear error. The integrity test (which MAY drive git) supplies the real map.
_READ_CLOCKS: frozenset[Clock] = frozenset({Clock.PROJECTION_EVENT, Clock.LAST_WRITE, Clock.NOW})
_COARSENING_CLOCKS: frozenset[Clock] = frozenset({Clock.COMMIT, Clock.DISTINCT_SNAPSHOT})


# ═══════════════════════════════════════════════════════════════════════════════════════════════
# Injectable sources (plan §6: "a small dataclass of optional store handles … every one injectable")
# ═══════════════════════════════════════════════════════════════════════════════════════════════


@dataclass
class SpineSources:
    """Optional handles on the audited stores. Tests inject fakes (in-memory stores seeded with
    controlled data); production resolves from config lazily (`resolve()`, the shadow-runner seam
    pattern). A None handle = that store is simply not part of this derivation."""

    ledger: RunLedger | None = None
    versions: VersionStore | None = None
    edges: EdgeStore | None = None
    derived: DerivedStore | None = None
    attestations: AttestationStore | None = None
    eval: EvalResultsStore | None = None
    catalog: VaultCatalog | None = None

    @classmethod
    def resolve(cls, config: Config | None = None) -> SpineSources:
        """Open each audited store from config — but ONLY where its file already exists, so the
        resolver has no side effects (never creates an empty DB). A store whose DuckDB file is
        write-locked (a running daemon) is skipped rather than raising; it surfaces as absent from
        the report's `stores_enumerated` (honest, no silent cap)."""
        from config.loader import get_config

        cfg = config or get_config()
        base = cfg.paths.derived_store.parent
        versions_p = base / "versions.sqlite"
        ledger_p = base / "run_ledger.sqlite"
        edges_p = base / "edges.sqlite"
        eval_p = base / "eval_results.duckdb"

        eval_src: EvalResultsStore | None = None
        if eval_p.exists():
            try:
                eval_src = EvalResultsStore(eval_p)
            except Exception:  # resilience guard: a write-locked DuckDB is skipped, never fatal
                eval_src = None

        return cls(
            versions=VersionStore(versions_p) if versions_p.exists() else None,
            ledger=RunLedger(ledger_p) if ledger_p.exists() else None,
            edges=EdgeStore(edges_p) if edges_p.exists() else None,
            derived=(
                DerivedStore(cfg.paths.derived_store)
                if cfg.paths.derived_store.exists() else None
            ),
            attestations=(
                AttestationStore(cfg.paths.attestation_store)
                if cfg.paths.attestation_store.exists() else None
            ),
            eval=eval_src,
            catalog=(
                VaultCatalog(cfg.paths.vault_catalog)
                if cfg.paths.vault_catalog.exists() else None
            ),
        )


# ═══════════════════════════════════════════════════════════════════════════════════════════════
# The builder — enumeration + generator edges (kept off the public Spine)
# ═══════════════════════════════════════════════════════════════════════════════════════════════


@dataclass
class _Builder:
    """Accumulates events, the produced-by index, and g1/g3 direct edges as each store is
    enumerated; `finalize()` computes g2 and enforces acyclicity."""

    events: dict[str, SpineEvent] = field(default_factory=dict)
    chain_of: dict[str, str] = field(default_factory=dict)          # event_id -> frontier key
    produced_by: dict[str, set[str]] = field(default_factory=dict)  # identifier -> minting events
    consumes: dict[str, tuple[str, ...]] = field(default_factory=dict)  # event_id -> refs it reads
    g13_edges: set[tuple[str, str, str]] = field(default_factory=set)   # (src, dst, gen) g1|g3
    present: list[str] = field(default_factory=list)

    def _add(self, store: str, chain_key: str, position: int | None,
             produces: tuple[str, ...], consumes: tuple[str, ...],
             refs: tuple[str, ...] | None = None) -> str:
        # `refs` (the displayed row metadata) defaults to produces ∪ consumes, but may be given
        # explicitly where an identifier belongs ON the row yet must NOT drive the g2 minter map —
        # an attestation's output_hashes (it is a proof-layer record, not the minter; see below).
        eid = _event_id(store, chain_key, position)
        row_refs = tuple(sorted(set(refs) if refs is not None else set(produces) | set(consumes)))
        self.events[eid] = SpineEvent(event_id=eid, store=store, stratum=_STRATUM[store],
                                      position=position, refs=row_refs)
        self.chain_of[eid] = f"{store}:{chain_key}"
        for p in produces:
            self.produced_by.setdefault(p, set()).add(eid)
        self.consumes[eid] = consumes
        return eid

    # -- g1 per-store append chains + the per-event produce/consume identifiers --------------------
    def versions(self, store: VersionStore) -> None:
        self.present.append("versions")
        prev_by_doc: dict[str, str] = {}
        rows = store._conn.execute(
            "SELECT doc_id, version_seq, digest FROM versions ORDER BY doc_id, version_seq"
        ).fetchall()
        for row in rows:
            doc_id, seq, digest = str(row["doc_id"]), int(row["version_seq"]), str(row["digest"])
            eid = self._add("versions", doc_id, seq, produces=(digest,), consumes=())
            prev = prev_by_doc.get(doc_id)
            if prev is not None:                              # per-doc chain (the op-seq exemplar)
                self.g13_edges.add((prev, eid, "g1"))
            prev_by_doc[doc_id] = eid

    def ledger(self, store: RunLedger) -> None:
        self.present.append("runledger")
        run_event: dict[str, str] = {}
        prev_run: str | None = None
        for row in store._conn.execute(
            "SELECT rowid, run_id, config_fingerprint, corpus_digest FROM dream_runs ORDER BY rowid"
        ).fetchall():
            rid, pos = str(row["run_id"]), int(row["rowid"])
            cf, cd = str(row["config_fingerprint"]), str(row["corpus_digest"])
            eid = self._add("runledger", "run", pos, produces=(rid,), consumes=(cf, cd))
            if prev_run is not None:                          # g1 run chain (rowid, not started_at)
                self.g13_edges.add((prev_run, eid, "g1"))
            prev_run, run_event[rid] = eid, eid
        last_claim: dict[str, str] = {}
        for row in store._conn.execute(
            "SELECT rowid, claim_id, run_id, support_json FROM dream_claims ORDER BY rowid"
        ).fetchall():
            cid, pos, rid = str(row["claim_id"]), int(row["rowid"]), str(row["run_id"])
            support = tuple(str(x) for x in json.loads(row["support_json"]))
            eid = self._add("runledger", "claim", pos, produces=(cid,), consumes=support)
            prior = last_claim.get(rid)                       # g3 recorded program order:
            if prior is not None:                             #   run → claim_1 → claim_2 → …
                self.g13_edges.add((prior, eid, "g3"))
            elif rid in run_event:
                self.g13_edges.add((run_event[rid], eid, "g3"))
            last_claim[rid] = eid

    def edges(self, store: EdgeStore) -> None:
        self.present.append("edges")
        prev: str | None = None
        for row in store._conn.execute(
            "SELECT rowid, edge_id, u, v FROM edges ORDER BY rowid"
        ).fetchall():
            edge_id, pos = str(row["edge_id"]), int(row["rowid"])
            u, v = str(row["u"]), str(row["v"])
            eid = self._add("edges", "edges", pos, produces=(edge_id,), consumes=(u, v))
            if prev is not None:                              # g1 append chain (rowid)
                self.g13_edges.add((prev, eid, "g1"))
            prev = eid

    def derived(self, store: DerivedStore) -> None:
        self.present.append("derived")
        rows = store._conn.execute(
            "SELECT rowid, id, derived_from, attestation_id "
            "FROM interpreted_artifacts ORDER BY rowid"
        ).fetchall()
        for row in rows:
            aid, pos = str(row["id"]), int(row["rowid"])
            df = tuple(str(x) for x in json.loads(row["derived_from"] or "[]"))
            att = row["attestation_id"]
            consumes = df + ((str(att),) if att is not None else ())
            # NO g1 rowid edge: the derived order IS the g2 `derived_from` DAG (module docstring;
            # §2.2 "ties broken by g2, never by wall" — INSERT OR REPLACE reassigns rowid).
            self._add("derived", "derived", pos, produces=(aid,), consumes=consumes)

    def attestations(self, store: AttestationStore) -> None:
        self.present.append("attestations")
        records = {a.id: a for a in store.all()}              # typed records; order irrelevant here
        prev: str | None = None
        for row in store._conn.execute(
            "SELECT rowid, id FROM attestations ORDER BY rowid"  # g1 append order = rowid (stable)
        ).fetchall():
            aid, pos = str(row["id"]), int(row["rowid"])
            rec = records.get(aid)
            if rec is None:
                produces: tuple[str, ...] = (aid,)
                consumes: tuple[str, ...] = ()
                row_refs: tuple[str, ...] = (aid,)
            else:
                # §2.8-5 (authoritative): attestation→attestation causal order is the
                # `derived_from_ids` PROVENANCE DAG (acyclic by construction — parents are PRIOR
                # attestations), NOT the raw output/input hash coincidence. An attestation is a
                # proof-layer record, not the MINTER of its outputs — each output is written to a
                # store whose OWN event mints it — so it produces ONLY its own content-addressed id.
                # If it also injected its output_hashes into the minter map, a shared corpus/config
                # digest listed as both an input and an output of many attestations would create
                # producer↔consumer edges in BOTH directions (the live-corpus 1467-event SCC).
                # Cross-store order survives: parentage via derived_from_ids; version→att via
                # input_hashes (versions/derived events are the true minters of those digests);
                # att→derived/eval via this attestation's own id (derived.attestation_id /
                # eval.evidence_ref). output_hashes still RIDE the row as displayed refs.
                produces = (aid,)
                consumes = (*rec.input_hashes, *rec.derived_from_ids)
                row_refs = (aid, *rec.output_hashes, *rec.input_hashes, *rec.derived_from_ids)
            eid = self._add("attestations", "attestation", pos,
                            produces=produces, consumes=consumes, refs=row_refs)
            if prev is not None:
                self.g13_edges.add((prev, eid, "g1"))
            prev = eid

    def eval(self, store: EvalResultsStore) -> None:
        self.present.append("eval")
        for r in store.query():                               # chain-less: position=None, g2 only
            k = r.key
            chain_key = hashlib.sha256(
                "\x00".join([k.spec_hash, k.corpus_ref, k.config_fingerprint,
                             str(k.seed), r.metric_name]).encode("utf-8")
            ).hexdigest()[:16]
            cons = [k.corpus_ref, k.config_fingerprint, k.spec_hash]
            if r.evidence_ref is not None:
                cons.append(r.evidence_ref)                   # may resolve to an attestation id
            self._add("eval", chain_key, None, produces=(), consumes=tuple(cons))

    def catalog(self, store: VaultCatalog) -> None:
        self.present.append("catalog")
        for row in store._conn.execute(
            "SELECT source_path, digest FROM vault_files ORDER BY source_path"  # keyed by path
        ).fetchall():
            sp, digest = str(row["source_path"]), str(row["digest"])
            # chain-less; produces its content digest (downstream consumers order after it)
            self._add("catalog", sp, None, produces=(digest,), consumes=())

    # -- g2 (reads-from) + acyclicity → the immutable Spine ---------------------------------------
    def finalize(
        self, coarsening_ticks: dict[Clock, dict[str, Hashable]] | None = None,
        cut_sources: CutSources | None = None,
    ) -> Spine:
        gen: set[tuple[str, str, str]] = set(self.g13_edges)
        refs_without_producer = 0
        for eid, refs in self.consumes.items():
            for ident in refs:
                producers = self.produced_by.get(ident)
                if not producers:                             # a ref no enumerated event minted —
                    refs_without_producer += 1                #   DROPPED, never fabricated (Item 2)
                    continue
                for p in producers:                           # generalized `producers_of`: p → e
                    if p != eid:
                        gen.add((p, eid, "g2"))

        succ: dict[str, set[str]] = {e: set() for e in self.events}
        for src, dst, _g in gen:
            succ[src].add(dst)
        _assert_acyclic(succ)                                 # construction invariant (§2.8-1)

        gen_edges = tuple(SpineEdge(src=s, dst=d, gen=g) for s, d, g in sorted(gen))
        return Spine(
            _events=dict(self.events),
            _succ=succ,
            _chain_of=dict(self.chain_of),
            _gen_edges=gen_edges,
            _produced_by={k: set(v) for k, v in self.produced_by.items()},
            _present=tuple(self.present),
            _refs_without_producer=refs_without_producer,
            _coarsening_ticks={c: dict(m) for c, m in (coarsening_ticks or {}).items()},
            _cut_sources=cut_sources or CutSources(),
        )


def _assert_acyclic(succ: dict[str, set[str]]) -> None:
    """Kahn topological sort; raise if not every node is processed (a cycle remains). Fail-closed —
    a cycle in `≼_derived` is a corrupted/forged reference, not a design problem (plan §10)."""
    indeg: dict[str, int] = dict.fromkeys(succ, 0)
    for outs in succ.values():
        for m in outs:
            indeg[m] += 1
    ready = deque(n for n, d in indeg.items() if d == 0)
    processed = 0
    while ready:
        n = ready.popleft()
        processed += 1
        for m in succ[n]:
            indeg[m] -= 1
            if indeg[m] == 0:
                ready.append(m)
    if processed != len(succ):
        cycle = sorted(n for n, d in indeg.items() if d > 0)
        raise SpineCycleError(
            f"cycle in ≼_derived over {len(cycle)} events — a corrupted/forged reference "
            f"(§2.8-1, fail-closed): {cycle[:8]}"
        )


# ═══════════════════════════════════════════════════════════════════════════════════════════════
# The spine
# ═══════════════════════════════════════════════════════════════════════════════════════════════


@dataclass
class Spine:
    """The derived causal event poset `(Ev, ≼)`. Construct via `derive()`; `≼` is the reflexive-
    transitive closure of the g1 ∪ g2 ∪ g3 generator edges (`generators()`)."""

    _events: dict[str, SpineEvent]
    _succ: dict[str, set[str]]                    # direct adjacency (g1∪g2∪g3); closure on restrict
    _chain_of: dict[str, str]                     # event_id -> "<store>:<chain-key>" frontier key
    _gen_edges: tuple[SpineEdge, ...]             # direct generator edges, sorted (deterministic)
    _produced_by: dict[str, set[str]]             # identifier -> minting event_ids
    _present: tuple[str, ...]
    _refs_without_producer: int
    # GC-2: externally-sourced ticks for the repo-backed coarsenings (COMMIT/DISTINCT_SNAPSHOT) —
    # {clock: {event_id: tick}}. Empty unless injected (core never sources commit SHAs itself).
    _coarsening_ticks: dict[Clock, dict[str, Hashable]] = field(default_factory=dict)
    # GC-3: injected certificate observables for `cut_at` (commit SHA / scheduler trough fact /
    # handoff path). Empty unless injected — a cut needing an unsourced certificate REFUSES (§2.4).
    _cut_sources: CutSources = field(default_factory=CutSources)

    @classmethod
    def derive(
        cls,
        sources: SpineSources,
        coarsening_ticks: dict[Clock, dict[str, Hashable]] | None = None,
        cut_sources: CutSources | None = None,
    ) -> Spine:
        """Enumerate the present stores and build `(Ev, ≼)`. Raises `SpineCycleError` if the derived
        order is not acyclic (an integrity failure — plan §10 STOP-and-raise).

        `coarsening_ticks` injects the externally-sourced ticks for the repo-backed coarsenings
        (COMMIT/DISTINCT_SNAPSHOT) — `{clock: {event_id: tick}}`. Core never sources commit SHAs
        itself (§2.10); the integrity test / a future consumer supplies the map.

        `cut_sources` (GC-3) injects the certificate observables `cut_at` sources from (the commit
        SHA, the scheduler quiescence fact, the sensing handoff path). Empty ⇒ `cut_at` refuses any
        cut whose strata require a certificate (never fabricates one, note §2.4)."""
        b = _Builder()
        if sources.versions is not None:
            b.versions(sources.versions)
        if sources.ledger is not None:
            b.ledger(sources.ledger)
        if sources.edges is not None:
            b.edges(sources.edges)
        if sources.derived is not None:
            b.derived(sources.derived)
        if sources.attestations is not None:
            b.attestations(sources.attestations)
        if sources.eval is not None:
            b.eval(sources.eval)
        if sources.catalog is not None:
            b.catalog(sources.catalog)
        return b.finalize(coarsening_ticks, cut_sources)

    # -- the pinned surface ------------------------------------------------------------------------
    def order(self, a: str, b: str) -> Order:
        """`order(e, e′) ∈ {before, after, concurrent}` over the transitive closure of ≼. An event
        is CONCURRENT with itself (≺ is irreflexive) and with any event neither reaches."""
        if a not in self._events:
            raise KeyError(f"unknown event {a!r}")
        if b not in self._events:
            raise KeyError(f"unknown event {b!r}")
        if a == b:
            return Order.CONCURRENT
        if b in self._reachable(a):
            return Order.BEFORE
        if a in self._reachable(b):
            return Order.AFTER
        return Order.CONCURRENT

    def frontier(self) -> dict[str, int]:
        """Per-chain latest positions — the vector of per-store chain positions a cut is read at
        (note §2.4). Keyed by "<store>:<chain-key>" (per-doc for versions); chain-less events
        (position=None) do not contribute."""
        out: dict[str, int] = {}
        for eid, ev in self._events.items():
            if ev.position is None:
                continue
            key = self._chain_of[eid]
            if key not in out or ev.position > out[key]:
                out[key] = ev.position
        return out

    def restrict(self, stratum: str) -> Spine:
        """N_s — the restriction of `(Ev, ≼)` to stratum-s events (the induced sub-poset: a ≼_s b
        iff a ≼ b in N and both events are in s). GC-2 consumes this."""
        kept = {eid for eid, ev in self._events.items() if ev.stratum == stratum}
        new_succ = {e: (self._reachable(e) & kept) for e in kept}   # induced transitive closure
        new_pb = {i: (evs & kept) for i, evs in self._produced_by.items() if evs & kept}
        return Spine(
            _events={e: self._events[e] for e in kept},
            _succ=new_succ,
            _chain_of={e: self._chain_of[e] for e in kept},
            _gen_edges=tuple(ed for ed in self._gen_edges if ed.src in kept and ed.dst in kept),
            _produced_by=new_pb,
            _present=self._present,
            _refs_without_producer=0,
            _coarsening_ticks={c: {e: t for e, t in m.items() if e in kept}
                               for c, m in self._coarsening_ticks.items()},
            _cut_sources=self._cut_sources,
        )

    def events(self) -> list[SpineEvent]:
        """Every event, in deterministic event_id order."""
        return [self._events[e] for e in sorted(self._events)]

    # -- extensions (GC-2/GC-3 + the §2.8-5 calibration) -------------------------------------------
    def generators(self) -> tuple[SpineEdge, ...]:
        """The DIRECT generator edges (g1/g2/g3), tagged — the edges ≼ is the closure of. The g2
        subset restricted to attestation events is the calibration oracle (§2.8-5)."""
        return self._gen_edges

    def producers_of(self, idents: set[str]) -> set[str]:
        """Generalizes `AttestationStore.producers_of` from attested actions to ALL store events:
        the event_ids whose produced identifiers intersect `idents` (the g2 generator, §2.2)."""
        out: set[str] = set()
        for i in idents:
            out |= self._produced_by.get(i, set())
        return out

    def report(self) -> SpineReport:
        """The no-silent-caps report (§2.9-5): enumerated stores, chain-less stores, and the stores
        beyond the §2.2 seven that this skeleton leaves unwired — NAMED, never silently absent."""
        chainless = tuple(sorted({ev.store for ev in self._events.values() if ev.position is None}))
        return SpineReport(
            stores_enumerated=self._present,
            event_count=len(self._events),
            edge_count=sum(len(s) for s in self._succ.values()),
            chainless_stores=chainless,
            refs_without_producer=self._refs_without_producer,
            stores_unwired=_UNWIRED_STORES,
        )

    # -- GC-2: the clock maps p_κ + N_s + proper time (plan §6; note §2.3 laws C1–C4) --------------
    def p(self, clock: Clock, event_id: str) -> Hashable:
        """`p_κ(e)` — the coarsening of the spine (= N) onto clock κ's index (plan §6; note §2.3).

        * WALL → RAISE (Law C4: wall is an exogenous coordinate, generates no order, has no p_κ).
        * N → identity `e` (the finest clock — the spine itself; singleton fibers).
        * N_S → `(stratum, e)`, the per-stratum event tick (rich N_s via `n_s(stratum)`).
        * read-clocks (projection_event / last_write / now) → `frontier_at(e.store)` — the borrowed
          write frontier (Law C3: read-clocks mint no events, they sample the frontier).
        * COMMIT / DISTINCT_SNAPSHOT → the injected external tick (`coarsening_ticks`); RAISES if
          the event has no injected tick (p_commit is partial over Ev — repo-backed events only)."""
        if event_id not in self._events:
            raise KeyError(f"unknown event {event_id!r}")
        if clock is Clock.WALL:
            raise ValueError(
                "wall is not a clock of Ev (Law C4) — it is an exogenous coordinate, generates no "
                "order and has no p_κ; register it only as a Rate(wall) denominator"
            )
        ev = self._events[event_id]
        if clock is Clock.N:
            return event_id                                   # identity — N is the finest (= spine)
        if clock is Clock.N_S:
            return (ev.stratum, event_id)                     # per-stratum event tick
        if clock in _READ_CLOCKS:
            return self.frontier_at(ev.store)                 # C3: borrow the write frontier
        if clock in _COARSENING_CLOCKS:
            ticks = self._coarsening_ticks.get(clock)
            if ticks is None or event_id not in ticks:
                raise ValueError(
                    f"clock {clock.value!r} has no p_κ tick for {event_id!r}: its tick is sourced "
                    f"externally (a git commit / content snapshot the event belongs to) and no "
                    f"store the spine reads carries it — inject via `coarsening_ticks` (bp-053 "
                    f"finding; core never shells to git, §2.10)"
                )
            return ticks[event_id]
        raise ValueError(f"clock {clock.value!r} has no registered p_κ over the spine")

    def fiber(self, clock: Clock, tick: Hashable) -> list[str]:
        """`p_κ⁻¹(tick)` — the event_ids that map to `tick`, sorted (deterministic). MUST be
        order-convex (Law C2): no event outside the tick lies ≼-between two inside it — "a commit is
        a RANGE of N" made a property (verify with `is_fiber_convex`). WALL RAISES (C4)."""
        if clock is Clock.WALL:
            raise ValueError("wall is not a clock of Ev (Law C4) — no fiber p_wall⁻¹ exists")
        if clock in _COARSENING_CLOCKS:
            ticks = self._coarsening_ticks.get(clock)
            if ticks is None:
                raise ValueError(
                    f"clock {clock.value!r} is not materialized — its ticks are sourced externally "
                    f"(git commit / content snapshot); inject via `coarsening_ticks` (bp-053)"
                )
            return sorted(eid for eid, t in ticks.items() if t == tick)
        return sorted(eid for eid in self._events if self.p(clock, eid) == tick)

    def is_fiber_convex(self, clock: Clock, tick: Hashable) -> bool:
        """Law C2 oracle: `p_κ⁻¹(tick)` is order-convex — no event OUTSIDE the fiber lies strictly
        ≼-between two events INSIDE it. This is the checkable form of "a commit is a range of N"
        (note §2.3 C2 / §2.8-3). The property tests + the integrity test drive this per clock."""
        members = set(self.fiber(clock, tick))
        if len(members) < 2:
            return True                                       # singletons / empties are convex
        for x in self._events:
            if x in members:
                continue
            # x is between two members iff some a ∈ F has a ≼ x and some b ∈ F has x ≼ b
            above = any(x in self._reachable(a) for a in members)
            if not above:
                continue
            if any(b in self._reachable(x) for b in members):
                return False
        return True

    def n_s(self, stratum: str) -> Spine:
        """N_s — the spine restricted to stratum `s` (an alias of `restrict`; the object per-stratum
        proper time and the locally-clocked superconnection are parked on, note §2.3/GC-N6)."""
        return self.restrict(stratum)

    def proper_time(self, a: str, b: str) -> tuple[int, bool]:
        """`(max-chain length, chain_complete)` between two events — the finding-0090 discipline.

        Proper time = the maximal-chain length in the N_s restriction (causal-set construction,
        GC-N6). It is EXACT (== event count) ONLY when the causal interval [a,b] is a TOTAL order
        (a single chain) — then `chain_complete=True`. Otherwise `chain_complete=False` and the bare
        count is NEVER sold as proper time (finding-0090):
          * different strata → cross-stratum, never one chain → `chain_complete=False`;
          * concurrent (neither ≼ the other) → no chain connects them → `(0, False)`;
          * comparable but the interval has concurrent events in between → `(longest_chain, False)`.
        Computed within `n_s(stratum)` when both events share a stratum (per-CHAIN per finding-0090,
        never per-stratum)."""
        for e in (a, b):
            if e not in self._events:
                raise KeyError(f"unknown event {e!r}")
        if self._events[a].stratum == self._events[b].stratum:
            return self.n_s(self._events[a].stratum)._chain_metric(a, b)   # per-stratum N_s
        length, _ = self._chain_metric(a, b)                  # cross-stratum: never chain_complete
        return (length, False)

    def frontier_at(self, store: str) -> int:
        """The observed write frontier of `store` — its latest chain position (Law C3 substrate:
        read-clocks borrow this, minting no event). 0 for an absent or chain-less-only store."""
        positions = [ev.position for ev in self._events.values()
                     if ev.store == store and ev.position is not None]
        return max(positions) if positions else 0

    # -- GC-3: certified cuts (plan §6; note §2.4 GC-N3 + the crossing-edge falsifier) ------------
    def cut_at(self, *, strata: frozenset[str]) -> CertifiedCut:
        """A certified consistent cut over `strata` — the per-chain frontier of those strata plus
        the composed certificate set they require, each SOURCED from its named observable
        (`_cut_sources`, injected at `derive`). REFUSES (`CutCertificateError`) if a certificate
        has no source or its observable is not quiescent — never fabricates one (plan §7 falsifier:
        a cut without its needed certificate, or a certificate from wall-time/inference)."""
        unknown = set(strata) - set(_STRATUM_CERTIFICATES)
        if unknown:
            raise CutCertificateError(
                f"cannot cut across unknown strata {sorted(unknown)!r} — no certificate rule "
                f"(known: {sorted(_STRATUM_CERTIFICATES)}); refusing rather than certifying blind"
            )
        fmap: dict[str, int] = {}
        for eid, ev in self._events.items():
            if ev.position is None or ev.stratum not in strata:
                continue                                  # chain-less / out-of-scope: no frontier
            key = self._chain_of[eid]
            if key not in fmap or ev.position > fmap[key]:
                fmap[key] = ev.position
        required: set[Certificate] = set()
        for s in strata:
            required |= _STRATUM_CERTIFICATES[s]
        evidence = tuple(sorted(self._source_certificate(c)
                                for c in sorted(required, key=lambda c: c.value)))
        return CertifiedCut(frontier=tuple(sorted(fmap.items())),
                            certificates=frozenset(required), evidence=evidence)

    def downset(self, cut: CertifiedCut) -> frozenset[str]:
        """`D(cut)` — the event down-set the frontier generates (note §2.4; plan §8). A CHAINED
        event is in D iff its chain is in the frontier and its position ≤ the frontier there. A
        CHAIN-LESS event (eval / catalog — position None) rides in iff it causally PRECEDES a
        chained seed event (a chain-less SOURCE like catalog whose digest a seed consumes) — so a
        real cut stays down-closed; a chain-less SINK (eval) is correctly never pulled in.
        Deliberately NOT auto-closed over chained events: that closure is exactly what
        `crossing_edges` verifies (else the soundness tooth would be vacuous)."""
        fmap = dict(cut.frontier)
        seed = {eid for eid, ev in self._events.items()
                if ev.position is not None and self._chain_of[eid] in fmap
                and ev.position <= fmap[self._chain_of[eid]]}
        result = set(seed)
        for eid, ev in self._events.items():
            if ev.position is None and self._reachable(eid) & seed:
                result.add(eid)                               # chain-less predecessor of the seed
        return frozenset(result)

    def crossing_edges(self, cut: CertifiedCut) -> list[tuple[str, str]]:
        """The §2.4 cut falsifier: generator edges `(a, b)` with `b ∈ D` but `a ∉ D` — an event
        inside the down-set reading from one outside it. MUST be `[]` for a certified cut; any hit
        is a certification bug (plan §7 — merge-blocking on real data). Only edges whose EXCLUDED
        source is IN the cut's covered domain (its chain is in the frontier) count: an edge exiting
        the cut's strata is out-of-scope (§2.7 GC-N8 — a cut reads only in-scope events), not a
        crossing."""
        d = self.downset(cut)
        fmap = dict(cut.frontier)
        crossings = [
            (e.src, e.dst) for e in self._gen_edges
            if e.dst in d and e.src not in d and self._chain_of.get(e.src) in fmap
        ]
        return sorted(crossings)

    def _source_certificate(self, cert: Certificate) -> str:
        """Source ONE certificate from its named observable in `_cut_sources`, or REFUSE. Never
        wall-time, never inference (note §2.4; plan §7 falsifier)."""
        src = self._cut_sources
        if cert is Certificate.COMMIT:
            if src.commit_sha is None:
                raise CutCertificateError(
                    "commit certificate absent: a repo-backed cut needs the commit SHA (the atomic "
                    "repo snapshot), and core never shells to git (§2.10) — inject it via "
                    "CutSources.commit_sha; refusing rather than fabricating a snapshot"
                )
            return f"commit:{src.commit_sha}"
        if cert is Certificate.TROUGH:
            if src.trough is None:
                raise CutCertificateError(
                    "trough certificate absent: a core-strata cut needs the scheduler's OWN "
                    "quiescence fact (JobQueue.counts()) — inject via CutSources.trough; refusing "
                    "rather than ASSUMING an empty queue"
                )
            if not src.trough.quiescent:
                raise CutCertificateError(
                    f"scheduler is NOT quiescent — {src.trough.queued} queued / "
                    f"{src.trough.running} running job(s) in flight; a cut across core strata "
                    f"needs an empty queue between trough jobs (§2.4-2), never a fabricated one"
                )
            return f"trough:{src.trough.trough_id}"
        if cert is Certificate.HANDOFF:
            if src.handoff is None:
                raise CutCertificateError(
                    "handoff certificate absent: a boundary-crossing cut needs the sensing handoff "
                    "path (requests/ + observations/) — inject it via CutSources.handoff; refusing "
                    "rather than assuming an empty handoff"
                )
            listing = self._handoff_listing(src.handoff)
            if listing:
                raise CutCertificateError(
                    f"sensing handoff is NOT empty — {len(listing)} in-flight edge↔core item(s) "
                    f"({listing[:4]}); a boundary cut needs requests/ and observations/ empty "
                    f"(note §2.4-3, core/sensing.py:236), never a fabricated emptiness"
                )
            digest = hashlib.sha256("\x00".join(listing).encode("utf-8")).hexdigest()[:16]
            return f"handoff:{digest}"
        raise CutCertificateError(f"unknown certificate {cert!r}")   # unreachable (enum-exhaustive)

    @staticmethod
    def _handoff_listing(handoff: Path) -> list[str]:
        """The sorted names in the handoff's requests/ and observations/ dirs — the handoff-empty
        observable (mirrored from `core/sensing.py`, never imported: the zone-boundary discipline).
        A filesystem read (no socket, no vault, no network) — the spine's only I/O beyond SELECT."""
        names: list[str] = []
        for sub in _HANDOFF_SUBDIRS:
            d = handoff / sub
            if d.is_dir():
                names.extend(p.name for p in d.iterdir())
        return sorted(names)

    # -- internal ----------------------------------------------------------------------------------
    def _reachable(self, start: str) -> set[str]:
        """Every event strictly reachable from `start` over the direct adjacency (BFS)."""
        seen: set[str] = set()
        queue = deque(self._succ.get(start, set()))
        while queue:
            n = queue.popleft()
            if n in seen:
                continue
            seen.add(n)
            queue.extend(self._succ.get(n, set()))
        return seen

    def _chain_metric(self, a: str, b: str) -> tuple[int, bool]:
        """`(longest-chain length, is_total)` for the causal interval [a,b] within THIS (possibly
        restricted) spine. `is_total` iff the interval is a chain (longest-chain len == its size —
        the exactness identity). Concurrent / self handled; a==b is the trivial 1-chain."""
        if a == b:
            return (1, True)
        if b in self._reachable(a):
            lo, hi = a, b
        elif a in self._reachable(b):
            lo, hi = b, a
        else:
            return (0, False)                                 # concurrent — no chain connects a,b
        interval = self._interval(lo, hi)
        length = self._longest_chain_len(interval)
        return (length, length == len(interval))

    def _interval(self, lo: str, hi: str) -> set[str]:
        """The causal interval `{x : lo ≼ x ≼ hi}` (inclusive), within this spine's order."""
        below_hi = self._reachable(lo) | {lo}                 # x with lo ≼ x
        return {x for x in below_hi if x == hi or hi in self._reachable(x)}

    def _longest_chain_len(self, nodes: set[str]) -> int:
        """Longest path by NODE count within the sub-DAG induced on `nodes` (Kahn topo DP). Correct
        on both the direct-adjacency spine and a restricted spine's transitively-closed `_succ`."""
        if not nodes:
            return 0
        indeg: dict[str, int] = dict.fromkeys(nodes, 0)
        for n in nodes:
            for m in self._succ.get(n, set()):
                if m in nodes:
                    indeg[m] += 1
        ready = deque(n for n in nodes if indeg[n] == 0)
        dist: dict[str, int] = dict.fromkeys(nodes, 1)
        while ready:
            n = ready.popleft()
            for m in self._succ.get(n, set()):
                if m not in nodes:
                    continue
                if dist[n] + 1 > dist[m]:
                    dist[m] = dist[n] + 1
                indeg[m] -= 1
                if indeg[m] == 0:
                    ready.append(m)
        return max(dist.values())
